use std::iter::FromIterator;

/// Every kind of node the parser can produce.
///
/// The variants are kept alphabetical by keep-sorted, which `//:keep_sorted_check`
/// enforces. Discriminants are assigned by position and are never persisted, so
/// re-sorting is safe.
#[derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    Copy,
    strum_macros::IntoStaticStr,
    strum_macros::EnumString,
    Hash,
    PartialOrd,
    Ord,
    Default,
)]
#[strum(serialize_all = "snake_case")]
pub enum SyntaxKind {
    // keep-sorted start sticky_prefixes=#[
    AccessStatement,
    ActionParameter,
    AddFileStatement,
    AddJarStatement,
    AggregateClause,
    AggregateOrderBy,
    AggregateOrderByClause,
    AliasExpression,
    AliasOperator,
    AllowConnections,
    AlterAccountStatement,
    AlterAggregateStatement,
    AlterBiCapacityStatement,
    AlterCapacityStatement,
    AlterCatalogStatement,
    AlterConnection,
    AlterConnectionRotateKeys,
    AlterConsumerGroupStatement,
    AlterDatabaseStatement,
    AlterDefaultPrivilegesGrant,
    AlterDefaultPrivilegesObjectPrivilege,
    AlterDefaultPrivilegesRevoke,
    AlterDefaultPrivilegesSchemaObject,
    AlterDefaultPrivilegesStatement,
    AlterDefaultPrivilegesToFromRoles,
    AlterDomainStatement,
    AlterDynamicTableStatement,
    AlterEventStatement,
    AlterExtensionStatement,
    AlterExternalTableStatement,
    AlterExternalVolumeStatement,
    AlterFileFormatSegment,
    AlterForeignTableActionSegment,
    AlterForeignTableStatement,
    AlterFunctionActionSegment,
    AlterFunctionStatement,
    AlterGroup,
    AlterIndexStatement,
    AlterMaskingPolicy,
    AlterMasterKeyStatement,
    AlterMaterializedViewActionSegment,
    AlterMaterializedViewSetOptionsStatement,
    AlterMaterializedViewStatement,
    AlterNetworkPolicyStatement,
    AlterOptionSegment,
    AlterOrganizationStatement,
    AlterPartitionFunctionStatement,
    AlterPartitionSchemeStatement,
    AlterPasswordPolicyStatement,
    AlterPipeSegment,
    AlterPolicyStatement,
    AlterProcedureActionSegment,
    AlterProcedureStatement,
    AlterProjectStatement,
    AlterPublicationStatement,
    AlterRenameStatement,
    AlterReservationStatement,
    AlterResourceMonitorStatement,
    AlterRoleStatement,
    AlterRowAccessPolicyStatement,
    AlterSchemaStatement,
    AlterSecretStatement,
    AlterSecurityPolicyStatement,
    AlterSequenceOptionsSegment,
    AlterSequenceStatement,
    AlterSessionSetStatement,
    AlterSessionStatement,
    AlterSessionUnsetClause,
    AlterShareStatement,
    AlterSourceSinkSizeStatement,
    AlterStageStatement,
    AlterStatisticsStatement,
    AlterStorageIntegrationStatement,
    AlterStreamStatement,
    AlterStreamlitStatement,
    AlterSubscription,
    AlterSystemStatement,
    AlterTableActionSegment,
    AlterTableAddColumn,
    AlterTableAlterColumn,
    AlterTableClusteringAction,
    AlterTableColumnClauses,
    AlterTableColumnStatement,
    AlterTableConstraintAction,
    AlterTableConstraintClauses,
    AlterTableConstraintStatement,
    AlterTableDistributePartitionStatement,
    AlterTableDropColumn,
    AlterTableModifyColumn,
    AlterTableProperties,
    AlterTableRenameColumn,
    AlterTableStatement,
    AlterTableSwitchStatement,
    AlterTableTableColumnAction,
    AlterTagStatement,
    AlterTaskSetClause,
    AlterTaskSpecialSetClause,
    AlterTaskStatement,
    AlterTaskUnsetClause,
    AlterTextSearchConfigurationStatement,
    AlterTrigger,
    AlterTypeStatement,
    AlterUserStatement,
    AlterViewStatement,
    AlterVirtualSchemaStatement,
    AlterVolumeStatement,
    AlterWarehouseStatement,
    Ampersand,
    AnalyzeCompressionStatement,
    AnalyzeStatement,
    AnalyzeTableStatement,
    ApplyChangesIntoStatement,
    ArnCatalogSchemaSegment,
    ArrayAccessor,
    ArrayExpression,
    ArrayJoinClause,
    ArrayLiteral,
    ArrayType,
    ArrayTypeSchema,
    ArrayUnnesting,
    AssertStatement,
    AssignmentOperator,
    AssignmentSegmentStatement,
    At,
    AtSign,
    AtSignLiteral,
    AtomicBeginEndBlock,
    Atsign,
    AuthorizationSegment,
    AutoOption,
    AvroFileFormatTypeParameters,
    AzureBlobStorageExternalStageParameters,
    BackQuote,
    BackupStorageRedundancy,
    BareFunction,
    Batch,
    BeginEndBlock,
    BeginStatement,
    BinaryLiteral,
    BinaryOperator,
    BindVariable,
    BitStringLiteral,
    BitValueLiteral,
    BlockComment,
    BooleanLiteral,
    Bracketed,
    BracketedArguments,
    BracketedIndexColumnListGrammar,
    BreakStatement,
    BteqKeyWordSegment,
    BteqStatement,
    BucketPath,
    BulkCollectIntoClause,
    BulkInsertStatement,
    BulkInsertWithSegment,
    ByteLengthLiteral,
    BytesDoubleQuote,
    BytesQuotedLiteral,
    BytesSingleQuote,
    CTEColumnList,
    CacheTable,
    CallOperator,
    CallSegment,
    CallStatement,
    Caret,
    CaseExpression,
    CastExpression,
    CastingOperator,
    CatalogReference,
    ChangesClause,
    CharacteristicStatement,
    CheckConstraintGrammar,
    CheckTableStatement,
    ChecksumTableStatement,
    ClearCache,
    CloseCursorStatement,
    CloseSchemaStatement,
    CloseStatement,
    ClusterByClause,
    ClusterBySegment,
    ClusterStatement,
    ClusterbyClause,
    Code,
    CollationClause,
    CollationReference,
    CollectStatUsingOptionClause,
    CollectStatisticsStatement,
    CollectionType,
    #[default]
    Colon,
    ColonDelimiter,
    ColonLiteral,
    ColonPrefix,
    ColumnAttributeSegment,
    ColumnConstraintSegment,
    ColumnDatatypeDefinition,
    ColumnDefinition,
    ColumnIndexIdentifierSegment,
    ColumnPathOperator,
    ColumnPropertiesSegment,
    ColumnReference,
    ColumnReferenceList,
    ColumnSelector,
    ColumnTtlSegment,
    ColumnTypeReference,
    ColumnsExpression,
    Comma,
    Command,
    Comment,
    CommentClause,
    CommentEqualsClause,
    CommentStatement,
    CommonTableExpression,
    ComparisonOperator,
    CompatibilityLevel,
    CompositeValueExpansion,
    CompoundTriggerStatement,
    CompressionType,
    ComputedColumnDefinition,
    ConflictAction,
    ConflictClause,
    ConflictTarget,
    ConnectByClause,
    ConnectbyClause,
    ConnectionConstraintGrammar,
    ConnectionDefinition,
    ConnectionLimitSegment,
    ConstraintPropertiesSegment,
    ConstraintStatement,
    ConsumerGroupParameter,
    ContinueStatement,
    ConvertToDeltaStatement,
    CopyFilesIntoLocationStatement,
    CopyFromStatement,
    CopyIntoLocationStatement,
    CopyIntoTableStatement,
    CopyOnErrorOption,
    CopyOptions,
    CopyStatement,
    CopyToStatement,
    CreateAdapterScript,
    CreateAggregateStatement,
    CreateAssignmentStatement,
    CreateAuthenticationPolicySegment,
    CreateCapacityStatement,
    CreateCastStatement,
    CreateCatalogStatement,
    CreateCloneStatement,
    CreateClusterReplicaStatement,
    CreateClusterStatement,
    CreateCollationStatement,
    CreateColumnstoreIndexStatement,
    CreateConnection,
    CreateConnectionStatement,
    CreateConsumerGroupStatement,
    CreateCortexSearchServiceStatement,
    CreateDatabaseFromShareStatement,
    CreateDatabaseRoleStatement,
    CreateDatabaseScopedCredentialStatement,
    CreateDatabaseStatement,
    CreateDatabaseWithOptions,
    CreateDatashareStatement,
    CreateDictionaryStatement,
    CreateDomainStatement,
    CreateEventStatement,
    CreateEventTableStatement,
    CreateExtensionStatement,
    CreateExternalDataSourceStatement,
    CreateExternalFileFormat,
    CreateExternalFunctionStatement,
    CreateExternalSchemaStatement,
    CreateExternalTableStatement,
    CreateExternalVolumeStatement,
    CreateFileFormatSegment,
    CreateForeignDataWrapper,
    CreateForeignTableStatement,
    CreateFulltextCatalogStatement,
    CreateFulltextIndexStatement,
    CreateFunctionStatement,
    CreateGroup,
    CreateIndexStatement,
    CreateLibraryStatement,
    CreateLoginStatement,
    CreateMasterKeyStatement,
    CreateMaterializedViewAsReplicaOfStatement,
    CreateMaterializedViewStatement,
    CreateModelStatement,
    CreateOperatorStatement,
    CreateOptionSegment,
    CreatePartitionFunctionStatement,
    CreatePartitionSchemeStatement,
    CreatePasswordPolicyStatement,
    CreatePolicyStatement,
    CreateProcedureStatement,
    CreatePublicationStatement,
    CreateReservationStatement,
    CreateResourceMonitorStatement,
    CreateRlsPolicyStatement,
    CreateRoleStatement,
    CreateRoutineLoadStatement,
    CreateRowAccessPolicyStatement,
    CreateSchemaStatement,
    CreateScriptingLuaScript,
    CreateSearchIndexStatement,
    CreateSecretStatement,
    CreateSecurityPolicyStatement,
    CreateSequenceOptionsSegment,
    CreateSequenceStatement,
    CreateServerRoleStatement,
    CreateServerStatement,
    CreateSinkKafkaStatement,
    CreateSnapshotTableStatement,
    CreateSourceKafkaStatement,
    CreateSourceLoadGeneratorStatement,
    CreateSourcePostgresStatement,
    CreateSqlFunctionStatement,
    CreateStageStatement,
    CreateStatement,
    CreateStatisticsStatement,
    CreateStreamStatement,
    CreateStreamlitStatement,
    CreateSubscription,
    CreateSynonymStatement,
    CreateTableAsSelectStatement,
    CreateTableAsStatement,
    CreateTableFunctionStatement,
    CreateTableGraphStatement,
    CreateTableOptionsStatement,
    CreateTableStatement,
    CreateTableUsingStatement,
    CreateTaskStatement,
    CreateTextSearchConfigurationStatement,
    CreateTrigger,
    CreateTriggerStatement,
    CreateTypeStatement,
    CreateUdfScript,
    CreateUserMappingStatement,
    CreateUserStatement,
    CreateVectorIndexStatement,
    CreateViewStatement,
    CreateVirtualSchemaStatement,
    CreateVirtualTableStatement,
    CreateVolumeStatement,
    CreateWidgetStatement,
    CsvCols,
    CsvFileFormatTypeParameters,
    CubeRollupClause,
    CursorDefinition,
    CursorFetchSegment,
    CursorOpenCloseSegment,
    Dash,
    DataFormatSegment,
    DataGovernancePolicyTagActionSegment,
    DataSourceFormat,
    DataType,
    DataTypeIdentifier,
    DatabaseEngine,
    DatabaseLinkReference,
    DatabaseReference,
    DatabaseRoleReference,
    DatabaseStatement,
    DateConstructorLiteral,
    DateFormat,
    DatePart,
    DatePartWeek,
    DatetimeLiteral,
    DatetimeTypeIdentifier,
    DeallocateCursorStatement,
    DeallocateSegment,
    DeallocateStatement,
    DeclareCursorVariable,
    DeclareOrReplaceVariableStatement,
    DeclareSegment,
    DeclareStatement,
    Dedent,
    DefaultCollate,
    DefinerSegment,
    DefinitionParameter,
    DefinitionParameters,
    DeleteStatement,
    DeleteTargetTable,
    DelimiterStatement,
    DescDatashareStatement,
    DescribeDetailStatement,
    DescribeHistoryStatement,
    DescribeStatement,
    DisableTrigger,
    DiscardStatement,
    DistributeByClause,
    DistributebyClause,
    DistributionSegment,
    Divide,
    DmlEventClause,
    DoStatement,
    Dollar,
    DollarLiteral,
    DollarNumericLiteral,
    DollarQuote,
    Dot,
    DoubleAmpersand,
    DoubleAtSignLiteral,
    DoubleDivide,
    DoubleQuote,
    DoubleVerticalBar,
    DropAggregateStatement,
    DropAssignmentStatement,
    DropCapacityStatement,
    DropCastStatement,
    DropCatalogStatement,
    DropCollationStatement,
    DropColumnClause,
    DropConnectionStatement,
    DropConsumerGroupStatement,
    DropDatabaseStatement,
    DropDatashareStatement,
    DropDictionaryStatement,
    DropDomainStatement,
    DropDynamicTableSegment,
    DropEventStatement,
    DropExtensionStatement,
    DropExternalTableStatement,
    DropExternalVolumeStatement,
    DropForeignTableStatement,
    DropFunctionStatement,
    DropIcebergTableStatement,
    DropIndexStatement,
    DropMasterKeyStatement,
    DropMaterializedViewStatement,
    DropModelStatement,
    DropModelstatement,
    DropObjectStatement,
    DropOwnedStatement,
    DropPasswordPolicyStatement,
    DropPolicyStatement,
    DropProcedureStatement,
    DropPublicationStatement,
    DropQuotaStatement,
    DropReservationStatement,
    DropResourceMonitorStatement,
    DropRlsPolicyStatement,
    DropRoleStatement,
    DropRowAccessPolicyStatement,
    DropSchemaStatement,
    DropScriptStatement,
    DropSearchIndexStatement,
    DropSecurityPolicy,
    DropSequenceStatement,
    DropSettingProfileStatement,
    DropStatement,
    DropStatisticsStatement,
    DropSubscription,
    DropSynonymStatement,
    DropTableFunctionStatement,
    DropTableStatement,
    DropTextSearchConfigurationStatement,
    DropTrigger,
    DropTriggerStatement,
    DropTypeStatement,
    DropUserStatement,
    DropVectorIndexStatement,
    DropViewStatement,
    DropVolumeStatement,
    DynamicTableLagIntervalSegment,
    DynamicTableOptions,
    Edition,
    ElseClause,
    EmitsSegment,
    EmptyStructLiteral,
    EmptyStructLiteralBrackets,
    EncryptedWithGrammar,
    EndAngleBracket,
    EndBracket,
    EndCurlyBracket,
    EndExcludeBracket,
    EndHint,
    EndOfFile,
    EndSquareBracket,
    Engine,
    EngineFunction,
    EngineType,
    EscapedIdentifier,
    EscapedSingleQuote,
    ExceptionBlockStatement,
    ExceptionCode,
    ExcludeBracketClose,
    ExcludeBracketOpen,
    ExclusionConstraintElement,
    ExecuteArrow,
    ExecuteAsClause,
    ExecuteFileStatement,
    ExecuteImmediate,
    ExecuteImmediateClause,
    ExecuteOption,
    ExecuteScriptStatement,
    ExecuteSegment,
    ExecuteStatement,
    ExecuteTaskClause,
    ExplainOption,
    ExplainStatement,
    ExplainVirtualStatement,
    ExportIntoClause,
    ExportOption,
    ExportStatement,
    Expression,
    ExtendClause,
    ExtensionReference,
    ExternalAccessIntegrationEquals,
    ExternalFileDelimitedTextClause,
    ExternalFileDelimitedTextFormatOptionsClause,
    ExternalFileDeltaClause,
    ExternalFileJsonClause,
    ExternalFileOrcClause,
    ExternalFileParquetClause,
    ExternalFileRcClause,
    ExternalLocation,
    ExternalVolumeReference,
    FatRightArrow,
    FbvCols,
    FetchClause,
    FetchCursorStatement,
    FetchStatement,
    File,
    FileCompression,
    FileEncoding,
    FileFormat,
    FileFormatSegment,
    FileKeyword,
    FileLiteral,
    FileOpts,
    FileReference,
    FileSpec,
    FileSpecFileGrowth,
    FileSpecFileName,
    FileSpecMaxSize,
    FileSpecNewName,
    FileSpecSize,
    FileSpecWithoutBracket,
    FileType,
    FilegroupClause,
    FilegroupName,
    FilestreamOnOptionStatement,
    FlushStatement,
    FlushStatisticsStatement,
    ForClause,
    ForInStatement,
    ForInStatements,
    ForLoopStatement,
    ForSystemTimeAsOfSegment,
    ForallStatement,
    FormatClause,
    FormatTypeOptions,
    FrameClause,
    FromAtExpression,
    FromBeforeExpression,
    FromClause,
    FromDatashareClause,
    FromExpression,
    FromExpressionElement,
    FromInUpdateClause,
    FromIntegrationClause,
    FromPivotExpression,
    FromUnpivotExpression,
    FullTextSearchOperator,
    Function,
    FunctionAssigner,
    FunctionAssignment,
    FunctionBody,
    FunctionContents,
    FunctionDefinition,
    FunctionForLoop,
    FunctionIfBranch,
    FunctionName,
    FunctionNameIdentifier,
    FunctionOptionSegment,
    FunctionParameterList,
    FunctionParameterListWithComments,
    FunctionReference,
    FunctionScriptTerminator,
    FunctionWhileLoop,
    GcsExternalStageParameters,
    GenerateManifestFileStatement,
    GeneratedColumnDefinition,
    GetDiagnosticsSegment,
    GetStatement,
    GlobOperator,
    GoStatement,
    GotoStatement,
    GrantDatashareStatement,
    GrantRevokeConnection,
    GrantRevokeConnectionRestricted,
    GrantRevokeImpersonation,
    GrantRevokeObjectPrivileges,
    GrantRevokeRoles,
    GrantRevokeSystemPrivileges,
    GrantToSegment,
    GraphTableConstraint,
    GroupAndOrderbyClause,
    GroupbyClause,
    GroupingExpressionList,
    GroupingSetsClause,
    HashIdentifier,
    HashPrefix,
    HavingClause,
    HelpStatement,
    HexadecimalLiteral,
    HierarchicalQueryClause,
    HintFunction,
    IamRoleClause,
    IcebergTableOptions,
    IcebergTransformation,
    Identifier,
    IdentifierClauseSegment,
    IdentifierList,
    IdentityGrammar,
    IfClause,
    IfStatement,
    IfStatements,
    IfThenStatement,
    ImpersonateStatement,
    Implicit,
    ImportColumns,
    ImportErrorDestination,
    ImportErrorsClause,
    ImportExportDbsrc,
    ImportFile,
    ImportForeignSchemaStatement,
    ImportFromClause,
    ImportScript,
    ImportStatement,
    Indent,
    IndexAccessMethod,
    IndexColumnDefinition,
    IndexDefinition,
    IndexElement,
    IndexElementOptions,
    IndexHintClause,
    IndexOption,
    IndexParameters,
    IndexReference,
    IndexType,
    IndexTypeReference,
    InitializeType,
    InlineComment,
    InlineDollarSign,
    InlinePathOperator,
    InsertOverwriteDirectoryHiveFmtStatement,
    InsertOverwriteDirectoryStatement,
    InsertOverwriteStatement,
    InsertRowAlias,
    InsertStatement,
    IntegerLiteral,
    IntervalExpression,
    IntervalLiteral,
    IntoClause,
    IntoOutfileClause,
    IntoTableClause,
    IsolationLevelClause,
    IterateStatement,
    JoinClause,
    JoinOnCondition,
    JsonFileFormatTypeParameters,
    JsonOperator,
    JsonPath,
    JsonTableColumnDefinition,
    JsonTableColumnsClause,
    JsonTableFunctionContents,
    KerberosAuth,
    Keyword,
    KillStatement,
    LabelSegment,
    Lambda,
    LambdaArrow,
    LambdaFunction,
    LanguageClause,
    LateralViewClause,
    LdapAuth,
    LeadingDot,
    LeaveStatement,
    LikeOperator,
    LikeOptionSegment,
    LimitClause,
    LimitClauseComponent,
    ListComprehension,
    ListFileStatement,
    ListJarStatement,
    ListStatement,
    ListaggOverflowClause,
    ListaggOverflowClauseSegment,
    ListenStatement,
    Literal,
    LoadDataStatement,
    LoadStatement,
    LocalAlias,
    LocalAliasSegment,
    LockTableStatement,
    LogLevelEquals,
    LogicalFileName,
    LoginUserSegment,
    LoopStatement,
    LoopStatements,
    MagicCellSegment,
    MagicLine,
    MagicSingleLine,
    MagicStart,
    ManageRlsPolicyStatement,
    MapType,
    MapTypeSchema,
    MaskStatement,
    MasterKeyEncryptionOption,
    MatchCondition,
    MatchConditionClause,
    MatchRecognizeClause,
    MaterializeSize,
    MaxDuration,
    MaxLiteral,
    MergeDeleteClause,
    MergeInsertClause,
    MergeMatch,
    MergeStatement,
    MergeTreeOrderByClause,
    MergeUpdateClause,
    MergeWhenMatchedClause,
    MergeWhenNotMatchedClause,
    Meta,
    MetaCommand,
    MetaCommandQueryBuffer,
    MetaCommandStatement,
    Minus,
    MlTableExpression,
    MsckRepairTableStatement,
    MsckTableStatement,
    MultiStatementSegment,
    NakedIdentifier,
    NakedIdentifierAll,
    NamedArgument,
    NamedWindow,
    NamedWindowExpression,
    Newline,
    Not,
    NotMatchedByTargetClause,
    NotOperator,
    NotebookStart,
    NotifyStatement,
    NullLiteral,
    NumericLiteral,
    ObevoAnnotation,
    ObjectLiteral,
    ObjectLiteralElement,
    ObjectPrivilege,
    ObjectReference,
    ObjectUnpivoting,
    OffsetClause,
    OnClusterClause,
    OnPartitionOrFilegroupStatement,
    OnPartitionsClause,
    OpenCursorStatement,
    OpenSchemaStatement,
    OpenSymmetricKeyStatement,
    OpenidAuth,
    OpenjsonSegment,
    OpenjsonWithClause,
    OpenquerySegment,
    OpenrowsetSegment,
    OpenrowsetWithClause,
    OpenxmlSegment,
    OperationClassReference,
    Operator,
    OperatorClassReference,
    OptimizeTableStatement,
    Option,
    OptionClause,
    OptionIndicator,
    OptionsSegment,
    OracleAlterDatabaseLinkStatement,
    OracleAlterFunctionStatement,
    OracleAlterIndexStatement,
    OracleAlterPackageStatement,
    OracleAlterSessionStatement,
    OracleAlterSynonymStatement,
    OracleAlterTableStatement,
    OracleAlterTriggerStatement,
    OracleAssignmentOperator,
    OracleAtSign,
    OracleBatch,
    OracleBeginEndBlock,
    OracleBindVariable,
    OracleCaseExpression,
    OracleColumnDefinition,
    OracleColumnTypeReference,
    OracleCommentStatement,
    OracleCreateDatabaseLinkStatement,
    OracleCreateFunctionStatement,
    OracleCreatePackageStatement,
    OracleCreateProcedureStatement,
    OracleCreateSynonymStatement,
    OracleCreateTableStatement,
    OracleCreateTriggerStatement,
    OracleCreateTypeBodyStatement,
    OracleCreateTypeStatement,
    OracleCreateUserStatement,
    OracleCreateViewStatement,
    OracleDeclareSegment,
    OracleDeleteStatement,
    OracleDropDatabaseLinkStatement,
    OracleDropPackageStatement,
    OracleDropProcedureStatement,
    OracleDropSynonymStatement,
    OracleElseClause,
    OracleExecuteImmediateStatement,
    OracleExitStatement,
    OracleFetchStatement,
    OracleFunctionName,
    OracleIfClause,
    OracleIfThenStatement,
    OracleInsertStatement,
    OracleIntoClause,
    OracleListaggOverflowClause,
    OracleLoopStatement,
    OracleMergeUpdateClause,
    OracleNamedArgument,
    OracleNullStatement,
    OracleOpenForStatement,
    OracleOpenStatement,
    OracleOrderByClause,
    OraclePackageReference,
    OraclePowerOperator,
    OracleReferencingClause,
    OracleReturnStatement,
    OracleReturningClause,
    OracleRowTypeReference,
    OracleSqlplusVariable,
    OracleTableConstraint,
    OracleTableReference,
    OracleTransactionStatement,
    OracleTypeReference,
    OracleUpdateStatement,
    OracleValuesClause,
    OracleWhenClause,
    OracleWithinGroupClause,
    OrcFileFormatTypeParameters,
    OrderbyClause,
    OutputClause,
    OverClause,
    OverlapsClause,
    Parameter,
    ParameterAssigner,
    ParameterDirection,
    ParameterizedExpression,
    ParquetFileFormatTypeParameters,
    PartitionBoundSpec,
    PartitionBySegment,
    PartitionClause,
    PartitionSchemeClause,
    PartitionSchemeName,
    PartitionSegment,
    PartitionbyClause,
    PartitionedBySegment,
    PasswordAuth,
    PasswordPolicyOptions,
    PasswordPolicyReference,
    PathSegment,
    PatternExpression,
    PauseRoutineLoadStatement,
    Percent,
    PeriodSegment,
    PgTrgmOperator,
    PgvectorOperator,
    Pipe,
    PipeOperator,
    PipeOperatorClause,
    PipeStatement,
    PivotClause,
    PivotColumnReference,
    PivotForClause,
    PivotOperator,
    PivotSegment,
    Placeholder,
    Plus,
    PlusPriorInverse,
    PostTableExpression,
    PostgisOperator,
    PragmaReference,
    PragmaStatement,
    PreWhereClause,
    PreferenceTerm,
    PreferringClause,
    PreloadStatement,
    PrepareSegment,
    PrepareStatement,
    PrewhereClause,
    PrimitiveType,
    PrintStatement,
    ProcedureName,
    ProcedureNameIdentifier,
    ProcedureOption,
    ProcedureParameterList,
    ProcedureStatement,
    ProcedureStatements,
    PropertiesNakedIdentifier,
    PropertyNameIdentifier,
    PsqlVariable,
    PublicationObjects,
    PublicationReference,
    PublicationTable,
    PurgeBinaryLogsStatement,
    PutStatement,
    QualifiedOperator,
    QualifyClause,
    QueryHintSegment,
    Question,
    QuestionLiteral,
    QuestionMark,
    QuotedIdentifier,
    QuotedLiteral,
    QuotedStar,
    RaiseStatement,
    RaiserrorStatement,
    RangeOperator,
    Raw,
    RawComparisonOperator,
    RawDoubleQuote,
    RawQuotedLiteral,
    RawSingleQuote,
    ReassignOwnedStatement,
    RecompressReorganizeStatement,
    ReconfigureStatement,
    RecordType,
    RefCursorType,
    ReferencedColumnList,
    ReferencesConstraintGrammar,
    ReferentialActionSegment,
    RefreshMaterializedViewStatement,
    RefreshStatement,
    ReindexStatementSegment,
    RejectClause,
    RelationOption,
    RelationOptions,
    RelationalIndexOptions,
    RemoveStatement,
    RemoveWidgetStatement,
    RenameColumnClause,
    RenameStatement,
    RenameTableStatement,
    RepairTableStatement,
    RepeatStatement,
    RepeatStatements,
    ReplaceStatement,
    ReplaceTableStatement,
    ResetMasterStatement,
    ResetSessionAuthorizationStatement,
    ResetStatement,
    ResignalSegment,
    ResourceConstraint,
    ResourceMonitorOptions,
    RestoreTableStatement,
    ResumeRoutineLoadStatement,
    ReturnSegment,
    ReturnStatement,
    ReturningClause,
    RightArrow,
    RoleReference,
    RoutineLoadDataSourceProperties,
    RoutineLoadProperties,
    RowFormatClause,
    RowFormatDelimitedSegment,
    S3ExternalStageParameters,
    SampleExpression,
    ScalingPolicy,
    SchemaObjectProperties,
    SchemaReference,
    ScriptContent,
    ScriptReference,
    ScriptingBlockStatement,
    ScriptingDeclareStatement,
    ScriptingIfStatement,
    ScriptingLetStatement,
    ScriptingRaiseStatement,
    SearchOptimizationAction,
    SecurityLabelStatement,
    SelectApplyClause,
    SelectClause,
    SelectClauseElement,
    SelectClauseModifier,
    SelectExceptClause,
    SelectExcludeClause,
    SelectHint,
    SelectRenameClause,
    SelectReplaceClause,
    SelectStatement,
    SelectVariableAssignment,
    SemiStructuredElement,
    SemiStructuredExpression,
    Semicolon,
    SequenceNextValue,
    SequenceReference,
    SerdeMethod,
    ServerReference,
    ServiceObjective,
    SessionParameter,
    SetClause,
    SetClauseList,
    SetConstraintStatement,
    SetContextInfoStatement,
    SetExpression,
    SetLanguageStatement,
    SetLocalVariableSegment,
    SetNamesStatement,
    SetOperator,
    SetOperatorClause,
    SetQueryBandStatement,
    SetSchemaStatement,
    SetSegment,
    SetSessionAuthorizationStatement,
    SetSessionStatement,
    SetStatement,
    SetTimezoneStatement,
    SetTransactionStatement,
    SetVariableStatement,
    SettingsClause,
    ShowCreateStatement,
    ShowDatasharesStatement,
    ShowIndexesStatement,
    ShowMaterializedViewsStatement,
    ShowModelStatement,
    ShowStatement,
    SignIndicator,
    SignedQuotedLiteral,
    SimplifiedPivot,
    SimplifiedUnpivot,
    SingleQuote,
    SingleQuoteWithN,
    SizeLiteral,
    SizedArrayType,
    SkewedByClause,
    Slash,
    SlashBufferExecutor,
    Slice,
    SnowflakeKeywordExpression,
    SnowflakeTaskExpressionSegment,
    SortByClause,
    SortbyClause,
    SqlConfOption,
    SqlcmdCommandSegment,
    SqlcmdOperator,
    SquareQuote,
    StageEncryptionOption,
    StageParameters,
    StagePath,
    Star,
    StartAngleBracket,
    StartBracket,
    StartCurlyBracket,
    StartExcludeBracket,
    StartHint,
    StartSquareBracket,
    StartwithClause,
    Statement,
    StatementTerminator,
    StatisticsReference,
    StopRoutineLoadStatement,
    StorageLocation,
    StoringSegment,
    StructLiteral,
    StructType,
    StructTypeSchema,
    SubscriptionReference,
    Symbol,
    SymlinkFormatManifest,
    SynonymReference,
    SystemDistributedSegment,
    SystemFetchesSegment,
    SystemFileSegment,
    SystemFilesystemSegment,
    SystemFunctionName,
    SystemMergesSegment,
    SystemModelSegment,
    SystemMovesSegment,
    SystemParameter,
    SystemPrivilege,
    SystemReplicaSegment,
    SystemReplicatedSegment,
    SystemReplicationSegment,
    SystemStatement,
    SystemTtlMergesSegment,
    SystemUnfreezeSegment,
    SystemVariable,
    TableClausesSegment,
    TableClusterByClause,
    TableColumnCommentAction,
    TableConstraint,
    TableConstraintDefinition,
    TableContentDefinition,
    TableDistributionClause,
    TableDistributionIndexClause,
    TableDistributionPartitionClause,
    TableEndClause,
    TableEndClauseSegment,
    TableEngineFunction,
    TableExpression,
    TableIndexClause,
    TableIndexSegment,
    TableLikeClause,
    TableLocationClause,
    TableOptionStatement,
    TableReference,
    TableSpecificationSegment,
    TableTtlSegment,
    TablespaceReference,
    TagBracketedEquals,
    TagEquals,
    TagReference,
    TagStatement,
    TdColumnAttributeConstraint,
    TdPartitioningLevel,
    TdTableConstraint,
    TemplateLoop,
    TemporalQuery,
    TernaryColon,
    TextimageOnOptionStatement,
    ThrowStatement,
    Tilde,
    TimeZoneGrammar,
    TimingPointSection,
    TraceLevelEquals,
    TransactionStatement,
    TransformClause,
    TriggerCorrelationName,
    TriggerReference,
    TruncateAuditLogsStatement,
    TruncateStatement,
    TruncateTable,
    TryCatch,
    TsqlVariable,
    Tuple,
    TupleElementAccess,
    TupleTypeSchema,
    TypedArrayLiteral,
    TypedStructLiteral,
    UdfBody,
    UdfParamDotSyntax,
    UncacheTable,
    UndropSchemaStatement,
    UndropStatement,
    UnicodeDoubleQuote,
    UnicodeSingleQuote,
    Unlexable,
    UnlistenStatement,
    UnloadStatement,
    UnorderedSelectStatementSegment,
    Unparsable,
    UnpivotClause,
    UnpivotMultiColumn,
    UnpivotOperator,
    UnpivotSegment,
    UnpivotSingleColumn,
    UnquotedFilePath,
    UnquotedRelativeSqlFilePath,
    UnsetStatement,
    UpdateStatement,
    UpdateStatisticsStatement,
    UpsertClause,
    UpsertClauseList,
    UseCatalogStatement,
    UseDatabaseStatement,
    UseStatement,
    UsingClause,
    VacuumStatement,
    ValidationModeOption,
    ValuesClause,
    ValuesClauseElements,
    ValuesInsertClause,
    ValuesRangeClause,
    Variable,
    VersionIdentifier,
    VerticalBar,
    ViewReference,
    VolumeReference,
    WaitforStatement,
    WalrusOperator,
    WarehouseObjectProperties,
    WarehouseSize,
    WhenClause,
    WhereClause,
    WhileLoopStatement,
    WhileStatement,
    WhileStatements,
    Whitespace,
    WidgetNameIdentifier,
    WildcardExclude,
    WildcardExpression,
    WildcardIdentifier,
    WildcardPatternMatching,
    WildcardRename,
    WildcardReplace,
    WindowSpecification,
    WithCheckOption,
    WithCheckOptions,
    WithCompoundStatement,
    WithCubeRollupClause,
    WithDataClause,
    WithFill,
    WithInvalidForeignKeyClause,
    WithInvalidUniquePkClause,
    WithNoSchemaBindingClause,
    WithRollupClause,
    WithinGroupClause,
    WithingroupClause,
    WithordinalityClause,
    WktGeometryType,
    Word,
    XmlFileFormatTypeParameters,
    // keep-sorted end
}

impl SyntaxKind {
    pub fn indent_val(self) -> i8 {
        match self {
            SyntaxKind::Indent | SyntaxKind::Implicit => 1,
            SyntaxKind::Dedent => -1,
            _ => 0,
        }
    }
}

impl SyntaxKind {
    pub fn as_str(&self) -> &'static str {
        self.into()
    }
}

#[derive(Clone, PartialEq, Eq, Default)]
pub struct SyntaxSet([u64; 19]);

impl std::fmt::Debug for SyntaxSet {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_list().entries(self.iter()).finish()
    }
}

impl SyntaxSet {
    pub const EMPTY: SyntaxSet = Self([0; 19]);
    const SLICE_BITS: u16 = u64::BITS as u16;

    pub const fn new(kinds: &[SyntaxKind]) -> Self {
        let mut set = SyntaxSet::EMPTY;

        let mut index = 0;
        while index < kinds.len() {
            set = set.union(&Self::single(kinds[index]));
            index += 1;
        }

        set
    }

    pub const fn single(kind: SyntaxKind) -> Self {
        let kind = kind as u16;

        let index = (kind / Self::SLICE_BITS) as usize;

        debug_assert!(
            index < Self::EMPTY.0.len(),
            "Index out of bounds. Increase the size of the bitset array."
        );

        let shift = kind % Self::SLICE_BITS;
        let mask = 1 << shift;

        let mut bits = Self::EMPTY.0;
        bits[index] = mask;

        Self(bits)
    }

    pub fn is_empty(&self) -> bool {
        self == &SyntaxSet::EMPTY
    }

    pub fn insert(&mut self, value: SyntaxKind) {
        let set = std::mem::take(self);
        *self = set.union(&SyntaxSet::single(value));
    }

    pub const fn intersection(mut self, other: &Self) -> Self {
        let mut index = 0;

        while index < self.0.len() {
            self.0[index] &= other.0[index];
            index += 1;
        }

        self
    }

    pub const fn union(mut self, other: &Self) -> Self {
        let mut i = 0;

        while i < self.0.len() {
            self.0[i] |= other.0[i];
            i += 1;
        }

        self
    }

    pub const fn intersects(&self, other: &Self) -> bool {
        let mut i = 0;

        while i < self.0.len() {
            if self.0[i] & other.0[i] != 0 {
                return true;
            }
            i += 1;
        }

        false
    }

    pub const fn contains(&self, kind: SyntaxKind) -> bool {
        let kind = kind as u16;
        let index = kind as usize / Self::SLICE_BITS as usize;
        let shift = kind % Self::SLICE_BITS;
        let mask = 1 << shift;

        self.0[index] & mask != 0
    }

    pub const fn len(&self) -> usize {
        let mut len: u32 = 0;

        let mut index = 0;
        while index < self.0.len() {
            len += self.0[index].count_ones();
            index += 1;
        }

        len as usize
    }

    pub fn iter(&self) -> SyntaxSetIter {
        SyntaxSetIter {
            set: self.clone(),
            index: 0,
        }
    }
}

impl Extend<SyntaxKind> for SyntaxSet {
    fn extend<T: IntoIterator<Item = SyntaxKind>>(&mut self, iter: T) {
        let set = std::mem::take(self);
        *self = set.union(&SyntaxSet::from_iter(iter));
    }
}

impl IntoIterator for SyntaxSet {
    type Item = SyntaxKind;
    type IntoIter = SyntaxSetIter;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl IntoIterator for &SyntaxSet {
    type Item = SyntaxKind;
    type IntoIter = SyntaxSetIter;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl FromIterator<SyntaxKind> for SyntaxSet {
    fn from_iter<T: IntoIterator<Item = SyntaxKind>>(iter: T) -> Self {
        let mut set = SyntaxSet::EMPTY;

        for kind in iter {
            set.insert(kind);
        }

        set
    }
}

pub struct SyntaxSetIter {
    set: SyntaxSet,
    index: u16,
}

impl Iterator for SyntaxSetIter {
    type Item = SyntaxKind;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            let slice = self.set.0.get_mut(self.index as usize)?;
            let bit = slice.trailing_zeros() as u16;

            if bit < SyntaxSet::SLICE_BITS {
                *slice ^= 1 << bit;
                let value = self.index * SyntaxSet::SLICE_BITS + bit;
                return Some(unsafe { std::mem::transmute::<u16, SyntaxKind>(value) });
            }

            self.index += 1;
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let len = self.set.len();

        (len, Some(len))
    }
}
