CREATE CLUSTERED INDEX CI_DLI_STAGE_CBS_POPULATION_BASE ON STAGE.CBS_POPULATION_BASE (DATE_LAST_INSERTED);
GO
CREATE NONCLUSTERED INDEX NCI_TEST ON STAGE.CBS_POPULATION_BASE (GEMEENTE_CODE, GEMEENTE);