[project]
site_name = "sqruff"
docs_dir = "docs"
site_dir = "site"

nav = [
  { "Overview" = "index.md" },
  { "Installing Sqruff" = "getting-started/installation.md" },
  { "Using Sqruff" = [
    { "The CLI" = "usage/lint.md" },
    { "Configuring Sqruff" = "usage/configuration.md" },
    { "dbt" = "experimental/dbt.md" },
    { "Ignore errors" = "usage/noqa.md" },
    { "Ignore files" = "usage/ignore-files.md" },
  ] },
  { "Dialects" = "reference/dialects.md" },
  { "Rules" = "reference/rules.md" },
  { "Reference" = [
    { "CLI" = "reference/cli.md" },
    { "Templaters" = "reference/templaters.md" },
    { "Sample configurations" = "reference/sample-configurations.md" },
  ] },
  { "Contributing" = "development/contributing.md" },
  { "Community projects" = "community/community-projects.md" },
]

[project.theme]
variant = "classic"
