/// Canonical function casing for ClickHouse case-sensitive built-ins.
///
/// Keep this list sorted by lowercase key and update via:
/// `.hacking/scripts/add_clickhouse_function_casing.py`.
pub(crate) const CLICKHOUSE_FUNCTION_CASING: &[(&str, &str)] = &[
    // BEGIN CLICKHOUSE_FUNCTION_CASING_MAP
    ("__actionname", "__actionName"),
    ("__bitboolmaskand", "__bitBoolMaskAnd"),
    ("__bitboolmaskor", "__bitBoolMaskOr"),
    ("__bitswaplasttwo", "__bitSwapLastTwo"),
    ("__bitwrapperfunc", "__bitWrapperFunc"),
    ("__getscalar", "__getScalar"),
    ("__scalarsubqueryresult", "__scalarSubqueryResult"),
    ("accuratecast", "accurateCast"),
    ("accuratecastordefault", "accurateCastOrDefault"),
    ("accuratecastornull", "accurateCastOrNull"),
    ("acosh", "acosh"),
    ("adddays", "addDays"),
    ("addhours", "addHours"),
    ("addinterval", "addInterval"),
    ("addmicroseconds", "addMicroseconds"),
    ("addmilliseconds", "addMilliseconds"),
    ("addminutes", "addMinutes"),
    ("addmonths", "addMonths"),
    ("addnanoseconds", "addNanoseconds"),
    ("addquarters", "addQuarters"),
    ("addresstoline", "addressToLine"),
    ("addresstolinewithinlines", "addressToLineWithInlines"),
    ("addresstosymbol", "addressToSymbol"),
    ("addseconds", "addSeconds"),
    ("addtupleofintervals", "addTupleOfIntervals"),
    ("addweeks", "addWeeks"),
    ("addyears", "addYears"),
    ("aes_decrypt_mysql", "aes_decrypt_mysql"),
    ("aes_encrypt_mysql", "aes_encrypt_mysql"),
    ("aggthrow", "aggThrow"),
    ("alphatokens", "alphaTokens"),
    ("and", "and"),
    ("any", "any"),
    ("any_respect_nulls", "any_respect_nulls"),
    ("anyheavy", "anyHeavy"),
    ("anylast", "anyLast"),
    ("anylast_respect_nulls", "anyLast_respect_nulls"),
    ("appendtrailingcharifabsent", "appendTrailingCharIfAbsent"),
    ("argmax", "argMax"),
    ("argmin", "argMin"),
    ("array", "array"),
    ("arrayall", "arrayAll"),
    ("arrayauc", "arrayAUC"),
    ("arrayaucpr", "arrayAUCPR"),
    ("arrayavg", "arrayAvg"),
    ("arraycompact", "arrayCompact"),
    ("arrayconcat", "arrayConcat"),
    ("arraycount", "arrayCount"),
    ("arraycumsum", "arrayCumSum"),
    ("arraycumsumnonnegative", "arrayCumSumNonNegative"),
    ("arraydifference", "arrayDifference"),
    ("arraydistinct", "arrayDistinct"),
    ("arraydotproduct", "arrayDotProduct"),
    ("arrayelement", "arrayElement"),
    ("arrayelementornull", "arrayElementOrNull"),
    ("arrayenumerate", "arrayEnumerate"),
    ("arrayenumeratedense", "arrayEnumerateDense"),
    ("arrayenumeratedenseranked", "arrayEnumerateDenseRanked"),
    ("arrayenumerateuniq", "arrayEnumerateUniq"),
    ("arrayenumerateuniqranked", "arrayEnumerateUniqRanked"),
    ("arrayexists", "arrayExists"),
    ("arrayfill", "arrayFill"),
    ("arrayfilter", "arrayFilter"),
    ("arrayfirst", "arrayFirst"),
    ("arrayfirstindex", "arrayFirstIndex"),
    ("arrayfirstornull", "arrayFirstOrNull"),
    ("arrayflatten", "arrayFlatten"),
    ("arrayfold", "arrayFold"),
    ("arrayintersect", "arrayIntersect"),
    ("arrayjaccardindex", "arrayJaccardIndex"),
    ("arrayjoin", "arrayJoin"),
    ("arraylast", "arrayLast"),
    ("arraylastindex", "arrayLastIndex"),
    ("arraylastornull", "arrayLastOrNull"),
    ("arraylevenshteindistance", "arrayLevenshteinDistance"),
    ("arraylevenshteindistanceweighted", "arrayLevenshteinDistanceWeighted"),
    ("arraymap", "arrayMap"),
    ("arraymax", "arrayMax"),
    ("arraymin", "arrayMin"),
    ("arraynormalizedgini", "arrayNormalizedGini"),
    ("arraypartialreversesort", "arrayPartialReverseSort"),
    ("arraypartialsort", "arrayPartialSort"),
    ("arraypopback", "arrayPopBack"),
    ("arraypopfront", "arrayPopFront"),
    ("arrayproduct", "arrayProduct"),
    ("arraypushback", "arrayPushBack"),
    ("arraypushfront", "arrayPushFront"),
    ("arrayrandomsample", "arrayRandomSample"),
    ("arrayreduce", "arrayReduce"),
    ("arrayreduceinranges", "arrayReduceInRanges"),
    ("arrayresize", "arrayResize"),
    ("arrayreverse", "arrayReverse"),
    ("arrayreversefill", "arrayReverseFill"),
    ("arrayreversesort", "arrayReverseSort"),
    ("arrayreversesplit", "arrayReverseSplit"),
    ("arrayrocauc", "arrayROCAUC"),
    ("arrayrotateleft", "arrayRotateLeft"),
    ("arrayrotateright", "arrayRotateRight"),
    ("arrayshiftleft", "arrayShiftLeft"),
    ("arrayshiftright", "arrayShiftRight"),
    ("arrayshingles", "arrayShingles"),
    ("arraysimilarity", "arraySimilarity"),
    ("arrayslice", "arraySlice"),
    ("arraysort", "arraySort"),
    ("arraysplit", "arraySplit"),
    ("arraystringconcat", "arrayStringConcat"),
    ("arraysum", "arraySum"),
    ("arraysymmetricdifference", "arraySymmetricDifference"),
    ("arrayunion", "arrayUnion"),
    ("arrayuniq", "arrayUniq"),
    ("arraywithconstant", "arrayWithConstant"),
    ("arrayzip", "arrayZip"),
    ("arrayzipunaligned", "arrayZipUnaligned"),
    ("asinh", "asinh"),
    ("assumenotnull", "assumeNotNull"),
    ("atanh", "atanh"),
    ("avgweighted", "avgWeighted"),
    ("bar", "bar"),
    ("base58decode", "base58Decode"),
    ("base58encode", "base58Encode"),
    ("base64decode", "base64Decode"),
    ("base64encode", "base64Encode"),
    ("base64urldecode", "base64URLDecode"),
    ("base64urlencode", "base64URLEncode"),
    ("basename", "basename"),
    ("bitand", "bitAnd"),
    ("bitcount", "bitCount"),
    ("bithammingdistance", "bitHammingDistance"),
    ("bitmapand", "bitmapAnd"),
    ("bitmapandcardinality", "bitmapAndCardinality"),
    ("bitmapandnot", "bitmapAndnot"),
    ("bitmapandnotcardinality", "bitmapAndnotCardinality"),
    ("bitmapbuild", "bitmapBuild"),
    ("bitmapcardinality", "bitmapCardinality"),
    ("bitmapcontains", "bitmapContains"),
    ("bitmaphasall", "bitmapHasAll"),
    ("bitmaphasany", "bitmapHasAny"),
    ("bitmapmax", "bitmapMax"),
    ("bitmapmin", "bitmapMin"),
    ("bitmapor", "bitmapOr"),
    ("bitmaporcardinality", "bitmapOrCardinality"),
    ("bitmapsubsetinrange", "bitmapSubsetInRange"),
    ("bitmapsubsetlimit", "bitmapSubsetLimit"),
    ("bitmaptoarray", "bitmapToArray"),
    ("bitmaptransform", "bitmapTransform"),
    ("bitmapxor", "bitmapXor"),
    ("bitmapxorcardinality", "bitmapXorCardinality"),
    ("bitmasktoarray", "bitmaskToArray"),
    ("bitmasktolist", "bitmaskToList"),
    ("bitnot", "bitNot"),
    ("bitor", "bitOr"),
    ("bitpositionstoarray", "bitPositionsToArray"),
    ("bitrotateleft", "bitRotateLeft"),
    ("bitrotateright", "bitRotateRight"),
    ("bitshiftleft", "bitShiftLeft"),
    ("bitshiftright", "bitShiftRight"),
    ("bitslice", "bitSlice"),
    ("bittest", "bitTest"),
    ("bittestall", "bitTestAll"),
    ("bittestany", "bitTestAny"),
    ("bitxor", "bitXor"),
    ("blake3", "BLAKE3"),
    ("blocknumber", "blockNumber"),
    ("blockserializedsize", "blockSerializedSize"),
    ("blocksize", "blockSize"),
    ("boundingratio", "boundingRatio"),
    ("buildid", "buildId"),
    ("bytehammingdistance", "byteHammingDistance"),
    ("bytesize", "byteSize"),
    ("casewithexpr", "caseWithExpr"),
    ("casewithexpression", "caseWithExpression"),
    ("catboostevaluate", "catboostEvaluate"),
    ("categoricalinformationvalue", "categoricalInformationValue"),
    ("cbrt", "cbrt"),
    ("changeday", "changeDay"),
    ("changehour", "changeHour"),
    ("changeminute", "changeMinute"),
    ("changemonth", "changeMonth"),
    ("changesecond", "changeSecond"),
    ("changeyear", "changeYear"),
    ("cityhash64", "cityHash64"),
    ("clamp", "clamp"),
    ("comparesubstrings", "compareSubstrings"),
    ("concatassumeinjective", "concatAssumeInjective"),
    ("concatwithseparator", "concatWithSeparator"),
    ("concatwithseparatorassumeinjective", "concatWithSeparatorAssumeInjective"),
    ("contingency", "contingency"),
    ("convertcharset", "convertCharset"),
    ("corrmatrix", "corrMatrix"),
    ("corrstable", "corrStable"),
    ("cosh", "cosh"),
    ("cosinedistance", "cosineDistance"),
    ("countdigits", "countDigits"),
    ("countequal", "countEqual"),
    ("countmatches", "countMatches"),
    ("countmatchescaseinsensitive", "countMatchesCaseInsensitive"),
    ("countsubstringscaseinsensitive", "countSubstringsCaseInsensitive"),
    ("countsubstringscaseinsensitiveutf8", "countSubstringsCaseInsensitiveUTF8"),
    ("covarpop", "covarPop"),
    ("covarpopmatrix", "covarPopMatrix"),
    ("covarpopstable", "covarPopStable"),
    ("covarsamp", "covarSamp"),
    ("covarsampmatrix", "covarSampMatrix"),
    ("covarsampstable", "covarSampStable"),
    ("cramersv", "cramersV"),
    ("cramersvbiascorrected", "cramersVBiasCorrected"),
    ("currentdatabase", "currentDatabase"),
    ("currentprofiles", "currentProfiles"),
    ("currentqueryid", "currentQueryID"),
    ("currentroles", "currentRoles"),
    ("currentuser", "currentUser"),
    ("cutfragment", "cutFragment"),
    ("cutipv6", "cutIPv6"),
    ("cutquerystring", "cutQueryString"),
    ("cutquerystringandfragment", "cutQueryStringAndFragment"),
    ("cuttofirstsignificantsubdomain", "cutToFirstSignificantSubdomain"),
    ("cuttofirstsignificantsubdomaincustom", "cutToFirstSignificantSubdomainCustom"),
    ("cuttofirstsignificantsubdomaincustomrfc", "cutToFirstSignificantSubdomainCustomRFC"),
    ("cuttofirstsignificantsubdomaincustomwithwww", "cutToFirstSignificantSubdomainCustomWithWWW"),
    ("cuttofirstsignificantsubdomaincustomwithwwwrfc", "cutToFirstSignificantSubdomainCustomWithWWWRFC"),
    ("cuttofirstsignificantsubdomainrfc", "cutToFirstSignificantSubdomainRFC"),
    ("cuttofirstsignificantsubdomainwithwww", "cutToFirstSignificantSubdomainWithWWW"),
    ("cuttofirstsignificantsubdomainwithwwwrfc", "cutToFirstSignificantSubdomainWithWWWRFC"),
    ("cuturlparameter", "cutURLParameter"),
    ("cutwww", "cutWWW"),
    ("dameraulevenshteindistance", "damerauLevenshteinDistance"),
    ("datetime64tosnowflake", "dateTime64ToSnowflake"),
    ("datetime64tosnowflakeid", "dateTime64ToSnowflakeID"),
    ("datetimetosnowflake", "dateTimeToSnowflake"),
    ("datetimetosnowflakeid", "dateTimeToSnowflakeID"),
    ("datetrunc", "dateTrunc"),
    ("decodehtmlcomponent", "decodeHTMLComponent"),
    ("decodeurlcomponent", "decodeURLComponent"),
    ("decodeurlformcomponent", "decodeURLFormComponent"),
    ("decodexmlcomponent", "decodeXMLComponent"),
    ("decrypt", "decrypt"),
    ("defaultprofiles", "defaultProfiles"),
    ("defaultroles", "defaultRoles"),
    ("defaultvalueofargumenttype", "defaultValueOfArgumentType"),
    ("defaultvalueoftypename", "defaultValueOfTypeName"),
    ("deltasum", "deltaSum"),
    ("deltasumtimestamp", "deltaSumTimestamp"),
    ("demangle", "demangle"),
    ("denserank", "denseRank"),
    ("detectcharset", "detectCharset"),
    ("detectlanguage", "detectLanguage"),
    ("detectlanguagemixed", "detectLanguageMixed"),
    ("detectlanguageunknown", "detectLanguageUnknown"),
    ("detectprogramminglanguage", "detectProgrammingLanguage"),
    ("detecttonality", "detectTonality"),
    ("dictget", "dictGet"),
    ("dictgetall", "dictGetAll"),
    ("dictgetchildren", "dictGetChildren"),
    ("dictgetdate", "dictGetDate"),
    ("dictgetdateordefault", "dictGetDateOrDefault"),
    ("dictgetdatetime", "dictGetDateTime"),
    ("dictgetdatetimeordefault", "dictGetDateTimeOrDefault"),
    ("dictgetdescendants", "dictGetDescendants"),
    ("dictgetfloat32", "dictGetFloat32"),
    ("dictgetfloat32ordefault", "dictGetFloat32OrDefault"),
    ("dictgetfloat64", "dictGetFloat64"),
    ("dictgetfloat64ordefault", "dictGetFloat64OrDefault"),
    ("dictgethierarchy", "dictGetHierarchy"),
    ("dictgetint16", "dictGetInt16"),
    ("dictgetint16ordefault", "dictGetInt16OrDefault"),
    ("dictgetint32", "dictGetInt32"),
    ("dictgetint32ordefault", "dictGetInt32OrDefault"),
    ("dictgetint64", "dictGetInt64"),
    ("dictgetint64ordefault", "dictGetInt64OrDefault"),
    ("dictgetint8", "dictGetInt8"),
    ("dictgetint8ordefault", "dictGetInt8OrDefault"),
    ("dictgetipv4", "dictGetIPv4"),
    ("dictgetipv4ordefault", "dictGetIPv4OrDefault"),
    ("dictgetipv6", "dictGetIPv6"),
    ("dictgetipv6ordefault", "dictGetIPv6OrDefault"),
    ("dictgetordefault", "dictGetOrDefault"),
    ("dictgetornull", "dictGetOrNull"),
    ("dictgetstring", "dictGetString"),
    ("dictgetstringordefault", "dictGetStringOrDefault"),
    ("dictgetuint16", "dictGetUInt16"),
    ("dictgetuint16ordefault", "dictGetUInt16OrDefault"),
    ("dictgetuint32", "dictGetUInt32"),
    ("dictgetuint32ordefault", "dictGetUInt32OrDefault"),
    ("dictgetuint64", "dictGetUInt64"),
    ("dictgetuint64ordefault", "dictGetUInt64OrDefault"),
    ("dictgetuint8", "dictGetUInt8"),
    ("dictgetuint8ordefault", "dictGetUInt8OrDefault"),
    ("dictgetuuid", "dictGetUUID"),
    ("dictgetuuidordefault", "dictGetUUIDOrDefault"),
    ("dicthas", "dictHas"),
    ("dictisin", "dictIsIn"),
    ("displayname", "displayName"),
    ("distinctdynamictypes", "distinctDynamicTypes"),
    ("distinctjsonpaths", "distinctJSONPaths"),
    ("distinctjsonpathsandtypes", "distinctJSONPathsAndTypes"),
    ("divide", "divide"),
    ("dividedecimal", "divideDecimal"),
    ("domain", "domain"),
    ("domainrfc", "domainRFC"),
    ("domainwithoutwww", "domainWithoutWWW"),
    ("domainwithoutwwwrfc", "domainWithoutWWWRFC"),
    ("dotproduct", "dotProduct"),
    ("dumpcolumnstructure", "dumpColumnStructure"),
    ("dynamicelement", "dynamicElement"),
    ("dynamictype", "dynamicType"),
    ("e", "e"),
    ("editdistance", "editDistance"),
    ("editdistanceutf8", "editDistanceUTF8"),
    ("empty", "empty"),
    ("emptyarraydate", "emptyArrayDate"),
    ("emptyarraydatetime", "emptyArrayDateTime"),
    ("emptyarrayfloat32", "emptyArrayFloat32"),
    ("emptyarrayfloat64", "emptyArrayFloat64"),
    ("emptyarrayint16", "emptyArrayInt16"),
    ("emptyarrayint32", "emptyArrayInt32"),
    ("emptyarrayint64", "emptyArrayInt64"),
    ("emptyarrayint8", "emptyArrayInt8"),
    ("emptyarraystring", "emptyArrayString"),
    ("emptyarraytosingle", "emptyArrayToSingle"),
    ("emptyarrayuint16", "emptyArrayUInt16"),
    ("emptyarrayuint32", "emptyArrayUInt32"),
    ("emptyarrayuint64", "emptyArrayUInt64"),
    ("emptyarrayuint8", "emptyArrayUInt8"),
    ("enabledprofiles", "enabledProfiles"),
    ("enabledroles", "enabledRoles"),
    ("encodeurlcomponent", "encodeURLComponent"),
    ("encodeurlformcomponent", "encodeURLFormComponent"),
    ("encodexmlcomponent", "encodeXMLComponent"),
    ("encrypt", "encrypt"),
    ("endswith", "endsWith"),
    ("endswithutf8", "endsWithUTF8"),
    ("entropy", "entropy"),
    ("equals", "equals"),
    ("erf", "erf"),
    ("erfc", "erfc"),
    ("errorcodetoname", "errorCodeToName"),
    ("estimatecompressionratio", "estimateCompressionRatio"),
    ("evalmlmethod", "evalMLMethod"),
    ("exp10", "exp10"),
    ("exp2", "exp2"),
    ("exponentialmovingaverage", "exponentialMovingAverage"),
    ("exponentialtimedecayedavg", "exponentialTimeDecayedAvg"),
    ("exponentialtimedecayedcount", "exponentialTimeDecayedCount"),
    ("exponentialtimedecayedmax", "exponentialTimeDecayedMax"),
    ("exponentialtimedecayedsum", "exponentialTimeDecayedSum"),
    ("extract", "extract"),
    ("extractall", "extractAll"),
    ("extractallgroups", "extractAllGroups"),
    ("extractallgroupshorizontal", "extractAllGroupsHorizontal"),
    ("extractallgroupsvertical", "extractAllGroupsVertical"),
    ("extractgroups", "extractGroups"),
    ("extractkeyvaluepairs", "extractKeyValuePairs"),
    ("extractkeyvaluepairswithescaping", "extractKeyValuePairsWithEscaping"),
    ("extracttextfromhtml", "extractTextFromHTML"),
    ("extracturlparameter", "extractURLParameter"),
    ("extracturlparameternames", "extractURLParameterNames"),
    ("extracturlparameters", "extractURLParameters"),
    ("farmfingerprint64", "farmFingerprint64"),
    ("farmhash64", "farmHash64"),
    ("file", "file"),
    ("filesystemavailable", "filesystemAvailable"),
    ("filesystemcapacity", "filesystemCapacity"),
    ("filesystemunreserved", "filesystemUnreserved"),
    ("finalizeaggregation", "finalizeAggregation"),
    ("firstline", "firstLine"),
    ("firstsignificantsubdomain", "firstSignificantSubdomain"),
    ("firstsignificantsubdomaincustom", "firstSignificantSubdomainCustom"),
    ("firstsignificantsubdomaincustomrfc", "firstSignificantSubdomainCustomRFC"),
    ("firstsignificantsubdomainrfc", "firstSignificantSubdomainRFC"),
    ("flamegraph", "flameGraph"),
    ("flattentuple", "flattenTuple"),
    ("format", "format"),
    ("formatdatetime", "formatDateTime"),
    ("formatdatetimeinjodasyntax", "formatDateTimeInJodaSyntax"),
    ("formatquery", "formatQuery"),
    ("formatqueryornull", "formatQueryOrNull"),
    ("formatquerysingleline", "formatQuerySingleLine"),
    ("formatquerysinglelineornull", "formatQuerySingleLineOrNull"),
    ("formatreadabledecimalsize", "formatReadableDecimalSize"),
    ("formatreadablequantity", "formatReadableQuantity"),
    ("formatreadablesize", "formatReadableSize"),
    ("formatreadabletimedelta", "formatReadableTimeDelta"),
    ("formatrow", "formatRow"),
    ("formatrownonewline", "formatRowNoNewline"),
    ("fragment", "fragment"),
    ("fromdayssinceyearzero", "fromDaysSinceYearZero"),
    ("fromdayssinceyearzero32", "fromDaysSinceYearZero32"),
    ("frommodifiedjulianday", "fromModifiedJulianDay"),
    ("frommodifiedjuliandayornull", "fromModifiedJulianDayOrNull"),
    ("fromunixtimestamp", "fromUnixTimestamp"),
    ("fromunixtimestamp64micro", "fromUnixTimestamp64Micro"),
    ("fromunixtimestamp64milli", "fromUnixTimestamp64Milli"),
    ("fromunixtimestamp64nano", "fromUnixTimestamp64Nano"),
    ("fromunixtimestamp64second", "fromUnixTimestamp64Second"),
    ("fromunixtimestampinjodasyntax", "fromUnixTimestampInJodaSyntax"),
    ("fromutctimestamp", "fromUTCTimestamp"),
    ("fullhostname", "fullHostName"),
    ("fuzzbits", "fuzzBits"),
    ("gccmurmurhash", "gccMurmurHash"),
    ("gcd", "gcd"),
    ("generaterandomstructure", "generateRandomStructure"),
    ("generateserialid", "generateSerialID"),
    ("generatesnowflakeid", "generateSnowflakeID"),
    ("generateulid", "generateULID"),
    ("generateuuidv4", "generateUUIDv4"),
    ("generateuuidv7", "generateUUIDv7"),
    ("geodistance", "geoDistance"),
    ("geohashdecode", "geohashDecode"),
    ("geohashencode", "geohashEncode"),
    ("geohashesinbox", "geohashesInBox"),
    ("geotoh3", "geoToH3"),
    ("geotos2", "geoToS2"),
    ("getclienthttpheader", "getClientHTTPHeader"),
    ("levenshteindistance", "levenshteinDistance"),
    ("levenshteindistanceutf8", "levenshteinDistanceUTF8"),
    ("mapfromstring", "mapFromString"),
    ("mismatches", "mismatches"),
    ("timestampdiff", "timestampDiff"),
    ("tointervalday", "toIntervalDay"),
    ("tointervalhour", "toIntervalHour"),
    ("tointervalmicrosecond", "toIntervalMicrosecond"),
    ("tointervalmillisecond", "toIntervalMillisecond"),
    ("tointervalminute", "toIntervalMinute"),
    ("tointervalmonth", "toIntervalMonth"),
    ("tointervalnanosecond", "toIntervalNanosecond"),
    ("tointervalquarter", "toIntervalQuarter"),
    ("tointervalsecond", "toIntervalSecond"),
    ("tointervalweek", "toIntervalWeek"),
    ("tointervalyear", "toIntervalYear"),
    ("toyyyymmdd", "toYYYYMMDD"),

    // END CLICKHOUSE_FUNCTION_CASING_MAP
];

/// ClickHouse function names known to be case-insensitive.
///
/// For these functions, CP03 should follow user capitalisation policy instead of
/// forcing canonical case.
pub(crate) const CLICKHOUSE_CASE_INSENSITIVE_FUNCTIONS: &[&str] = &[
    // BEGIN CLICKHOUSE_CASE_INSENSITIVE_FUNCTIONS
    "_cast",
    "abs",
    "acos",
    "adddate",
    "age",
    "analysisofvariance",
    "anova",
    "any_value",
    "any_value_respect_nulls",
    "approx_top_count",
    "approx_top_k",
    "approx_top_sum",
    "arraypartialshuffle",
    "arrayshuffle",
    "ascii",
    "asin",
    "atan",
    "atan2",
    "avg",
    "bin",
    "byteswap",
    "cast",
    "ceil",
    "ceiling",
    "char",
    "coalesce",
    "concat",
    "concat_ws",
    "connection_id",
    "connectionid",
    "corr",
    "cos",
    "count",
    "countsubstrings",
    "covar_pop",
    "covar_samp",
    "crc32",
    "crc32ieee",
    "crc64",
    "current_database",
    "current_query_id",
    "current_schemas",
    "current_user",
    "currentschemas",
    "database",
    "date",
    "date_format",
    "date_trunc",
    "datediff",
    "datename",
    "degrees",
    "dense_rank",
    "exp",
    "factorial",
    "first_value",
    "first_value_respect_nulls",
    "flatten",
    "floor",
    "format_bytes",
    "fqdn",
    "from_base64",
    "from_days",
    "from_unixtime",
    "from_utc_timestamp",
    "last_value",
    "last_value_respect_nulls",
    "scalarproduct",
    "schema",
    "str_to_map",
    "to_base64",
    "user",
    // END CLICKHOUSE_CASE_INSENSITIVE_FUNCTIONS
];

pub(crate) fn canonical_clickhouse_function_name(function_name: &str) -> Option<&'static str> {
    let lookup_key = function_name.to_ascii_lowercase();
    CLICKHOUSE_FUNCTION_CASING
        .binary_search_by_key(&lookup_key.as_str(), |(lowercase_name, _)| *lowercase_name)
        .ok()
        .map(|index| CLICKHOUSE_FUNCTION_CASING[index].1)
}

pub(crate) fn is_clickhouse_case_insensitive_function(function_name: &str) -> bool {
    let lookup_key = function_name.to_ascii_lowercase();
    CLICKHOUSE_CASE_INSENSITIVE_FUNCTIONS
        .binary_search(&lookup_key.as_str())
        .is_ok()
}

#[cfg(test)]
mod tests {
    use super::CLICKHOUSE_CASE_INSENSITIVE_FUNCTIONS;
    use super::CLICKHOUSE_FUNCTION_CASING;
    use super::canonical_clickhouse_function_name;
    use super::is_clickhouse_case_insensitive_function;

    #[test]
    fn clickhouse_function_casing_lookup_works() {
        assert_eq!(
            canonical_clickhouse_function_name("tointervalminute"),
            Some("toIntervalMinute")
        );
        assert_eq!(
            canonical_clickhouse_function_name("TOINTERVALMONTH"),
            Some("toIntervalMonth")
        );
        assert_eq!(
            canonical_clickhouse_function_name("arrayauc"),
            Some("arrayAUC")
        );
        assert_eq!(canonical_clickhouse_function_name("sum"), None);
    }

    #[test]
    fn clickhouse_function_casing_entries_are_sorted() {
        for pair in CLICKHOUSE_FUNCTION_CASING.windows(2) {
            assert!(pair[0].0 <= pair[1].0, "entries must be sorted");
        }
    }

    #[test]
    fn clickhouse_case_insensitive_lookup_works() {
        assert!(is_clickhouse_case_insensitive_function("ANY_VALUE"));
        assert!(is_clickhouse_case_insensitive_function("BYTESWAP"));
        assert!(is_clickhouse_case_insensitive_function("CAST"));
        assert!(is_clickhouse_case_insensitive_function("concat_ws"));
        assert!(is_clickhouse_case_insensitive_function("CONNECTION_ID"));
        assert!(is_clickhouse_case_insensitive_function("covar_pop"));
        assert!(is_clickhouse_case_insensitive_function("COVAR_SAMP"));
        assert!(is_clickhouse_case_insensitive_function("CRC32IEEE"));
        assert!(is_clickhouse_case_insensitive_function("current_schemas"));
        assert!(is_clickhouse_case_insensitive_function("DATABASE"));
        assert!(is_clickhouse_case_insensitive_function("DATE"));
        assert!(is_clickhouse_case_insensitive_function("DATE_FORMAT"));
        assert!(is_clickhouse_case_insensitive_function("DATE_TRUNC"));
        assert!(is_clickhouse_case_insensitive_function("DEGREES"));
        assert!(is_clickhouse_case_insensitive_function("DENSE_RANK"));
        assert!(is_clickhouse_case_insensitive_function("EXP"));
        assert!(is_clickhouse_case_insensitive_function("FACTORIAL"));
        assert!(is_clickhouse_case_insensitive_function("USER"));
        assert!(is_clickhouse_case_insensitive_function(
            "first_value_respect_nulls"
        ));
        assert!(is_clickhouse_case_insensitive_function("FLOOR"));
        assert!(is_clickhouse_case_insensitive_function("FORMAT_BYTES"));
        assert!(is_clickhouse_case_insensitive_function("FQDN"));
        assert!(is_clickhouse_case_insensitive_function("FROM_BASE64"));
        assert!(is_clickhouse_case_insensitive_function("FROM_DAYS"));
        assert!(is_clickhouse_case_insensitive_function("FROM_UNIXTIME"));
        assert!(is_clickhouse_case_insensitive_function("FROM_UTC_TIMESTAMP"));
        assert!(is_clickhouse_case_insensitive_function("to_base64"));
        assert!(is_clickhouse_case_insensitive_function("BIN"));
        assert!(is_clickhouse_case_insensitive_function("AVG"));
        assert!(is_clickhouse_case_insensitive_function("SCALARPRODUCT"));
        assert!(is_clickhouse_case_insensitive_function("STR_TO_MAP"));
        assert!(!is_clickhouse_case_insensitive_function("anyRespectNulls"));
    }

    #[test]
    fn clickhouse_case_insensitive_entries_are_sorted() {
        for pair in CLICKHOUSE_CASE_INSENSITIVE_FUNCTIONS.windows(2) {
            assert!(pair[0] <= pair[1], "entries must be sorted");
        }
    }
}
