/// Datbricks reserved keywords which can be found https://docs.databricks.com/sql/language-manual/sql-ref-reserved-words.html
pub(crate) const RESERVED_KEYWORDS: &[&str] = &[
    "ANTI",
    "CROSS",
    "EXCEPT",
    "FULL",
    "INNER",
    "INTERSECT",
    "JOIN",
    "LATERAL",
    "LEFT",
    "MINUS",
    "NATURAL",
    "ON",
    "RIGHT",
    "SEMI",
    "UNION",
    "USING",
];

pub(crate) const UNRESERVED_KEYWORDS: &[&str] = &[
    "CATALOG",
    "COMPENSATION",
    "CRON",
    "ENFORCED",
    "EVOLUTION",
    "FEATURE",
    "IDENTIFIER",
    "MANAGED",
    "MASK",
    "NORELY",
    "OPTIMIZATION",
    "OPTIMIZE",
    "PREDICTIVE",
    "PROVIDER",
    "PYTHON",
    "RECIPIENT",
    "RELY",
    "SCHEDULE",
    "SQL",
    "TAGS",
    "TIMESERIES",
    "VOLUME",
    "VOLUMES",
    "ZORDER",
];
