//! Apache Doris SQL dialect, based on MySQL.
use super::mysql;
use crate::doris_keywords::{DORIS_RESERVED_KEYWORDS, DORIS_UNRESERVED_KEYWORDS};
use sqruff_lib_core::dialects::Dialect;
use sqruff_lib_core::dialects::init::{DialectConfig, DialectKind};
use sqruff_lib_core::dialects::syntax::SyntaxKind;
use sqruff_lib_core::helpers::{Config, ToMatchable};
use sqruff_lib_core::parser::grammar::Ref;
use sqruff_lib_core::parser::grammar::anyof::{one_of, optionally_bracketed};
use sqruff_lib_core::parser::grammar::delimited::Delimited;
use sqruff_lib_core::parser::grammar::sequence::{Bracketed, Sequence};
use sqruff_lib_core::parser::matchable::MatchableTrait;
use sqruff_lib_core::parser::node_matcher::NodeMatcher;
use sqruff_lib_core::parser::parsers::StringParser;
use sqruff_lib_core::value::Value;
sqruff_lib_core::dialect_config!(DorisDialectConfig {});
pub fn dialect(config: Option<&Value>) -> Dialect {
    let _dialect_config: DorisDialectConfig = config
        .map(DorisDialectConfig::from_value)
        .unwrap_or_default();
    raw_dialect().config(|dialect| dialect.expand())
}
pub fn raw_dialect() -> Dialect {
    let mut doris = mysql::raw_dialect();
    doris.name = DialectKind::Doris;
    doris
        .sets_mut("unreserved_keywords")
        .extend(DORIS_UNRESERVED_KEYWORDS.split_whitespace());
    doris.sets_mut("reserved_keywords").clear();
    doris
        .sets_mut("reserved_keywords")
        .extend(DORIS_RESERVED_KEYWORDS.split_whitespace());
    let engines = [
        "OLAP",
        "MYSQL",
        "ELASTICSEARCH",
        "HIVE",
        "HUDI",
        "ICEBERG",
        "JDBC",
        "BROKER",
    ];
    doris.sets_mut("engine_types").extend(engines);
    doris.add([(
        "EngineTypeSegment".into(),
        one_of(
            engines
                .into_iter()
                .map(|engine| StringParser::new(engine, SyntaxKind::EngineType).to_matchable())
                .collect(),
        )
        .to_matchable()
        .into(),
    )]);

    doris.replace_grammar(
        "ColumnDefinitionSegment",
        doris
            .grammar("ColumnDefinitionSegment")
            .match_grammar(&doris)
            .unwrap()
            .copy(
                Some(vec![
                    one_of(vec![
                        Ref::keyword("MAX").to_matchable(),
                        Ref::keyword("MIN").to_matchable(),
                        Ref::keyword("REPLACE").to_matchable(),
                        Ref::keyword("SUM").to_matchable(),
                        Ref::keyword("BITMAP_UNION").to_matchable(),
                        Ref::keyword("HLL_UNION").to_matchable(),
                        Ref::keyword("QUANTILE_UNION").to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                ]),
                None,
                None,
                None,
                Vec::new(),
                false,
            ),
    );
    doris.replace_grammar(
        "CreateTableStatementSegment",
        Sequence::new(vec![
            Ref::keyword("CREATE").to_matchable(),
            Ref::new("OrReplaceGrammar").optional().to_matchable(),
            Ref::keyword("TEMPORARY").optional().to_matchable(),
            Ref::keyword("EXTERNAL").optional().to_matchable(),
            Ref::keyword("TABLE").to_matchable(),
            Ref::new("IfNotExistsGrammar").optional().to_matchable(),
            Ref::new("TableReferenceSegment").to_matchable(),
            one_of(vec![
                Sequence::new(vec![
                    Bracketed::new(vec![
                        Delimited::new(vec![
                            one_of(vec![
                                Ref::new("TableConstraintSegment").to_matchable(),
                                Ref::new("ColumnDefinitionSegment").to_matchable(),
                                Ref::new("IndexDefinitionSegment").to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                    Sequence::new(vec![
                        Ref::keyword("ENGINE").to_matchable(),
                        Ref::new("EqualsSegment").to_matchable(),
                        Ref::new("EngineTypeSegment").to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                    Sequence::new(vec![
                        one_of(vec![
                            Sequence::new(vec![
                                Ref::keyword("DUPLICATE").to_matchable(),
                                Ref::keyword("KEY").to_matchable(),
                            ])
                            .to_matchable(),
                            Sequence::new(vec![
                                Ref::keyword("AGGREGATE").to_matchable(),
                                Ref::keyword("KEY").to_matchable(),
                            ])
                            .to_matchable(),
                            Sequence::new(vec![
                                Ref::keyword("UNIQUE").to_matchable(),
                                Ref::keyword("KEY").to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                        Bracketed::new(vec![
                            Delimited::new(vec![Ref::new("ColumnReferenceSegment").to_matchable()])
                                .to_matchable(),
                        ])
                        .to_matchable(),
                        Sequence::new(vec![
                            Ref::keyword("CLUSTER").to_matchable(),
                            Ref::keyword("BY").to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![
                                    Ref::new("ColumnReferenceSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .config(|this| this.optional())
                        .to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                    Ref::new("CommentClauseSegment").optional().to_matchable(),
                    Ref::new("PartitionSegment").optional().to_matchable(),
                    Ref::new("DistributionSegment").optional().to_matchable(),
                    Ref::new("RollupSegment").optional().to_matchable(),
                    Sequence::new(vec![
                        Ref::keyword("PROPERTIES").to_matchable(),
                        Bracketed::new(vec![
                            Delimited::new(vec![
                                Sequence::new(vec![
                                    Ref::new("QuotedLiteralSegment").to_matchable(),
                                    Ref::new("EqualsSegment").to_matchable(),
                                    Ref::new("QuotedLiteralSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("LIKE").to_matchable(),
                    Ref::new("TableReferenceSegment").to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Sequence::new(vec![
                        Ref::keyword("ENGINE").to_matchable(),
                        Ref::new("EqualsSegment").to_matchable(),
                        Ref::new("EngineTypeSegment").to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                    Ref::new("CommentClauseSegment").optional().to_matchable(),
                    Sequence::new(vec![
                        Ref::keyword("PROPERTIES").to_matchable(),
                        Bracketed::new(vec![
                            Delimited::new(vec![
                                Sequence::new(vec![
                                    Ref::new("QuotedLiteralSegment").to_matchable(),
                                    Ref::new("EqualsSegment").to_matchable(),
                                    Ref::new("QuotedLiteralSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                    Ref::keyword("AS").to_matchable(),
                    optionally_bracketed(vec![Ref::new("SelectableGrammar").to_matchable()])
                        .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable(),
        ])
        .to_matchable(),
    );
    doris.replace_grammar(
        "ColumnConstraintSegment",
        one_of(vec![
            mysql::column_constraint_grammar(false),
            Sequence::new(vec![
                Ref::keyword("AS").to_matchable(),
                Ref::new("ExpressionSegment").to_matchable(),
            ])
            .to_matchable(),
            Sequence::new(vec![
                Ref::keyword("GENERATED").to_matchable(),
                Ref::keyword("ALWAYS").to_matchable(),
                Ref::keyword("AS").to_matchable(),
                Bracketed::new(vec![Ref::new("ExpressionSegment").to_matchable()]).to_matchable(),
            ])
            .to_matchable(),
        ])
        .to_matchable(),
    );
    doris.add([(
        "PartitionSegment".into(),
        NodeMatcher::new(SyntaxKind::PartitionSegment, |_| {
            one_of(vec![
                Sequence::new(vec![
                    Ref::keyword("AUTO").to_matchable(),
                    Ref::keyword("PARTITION").to_matchable(),
                    Ref::keyword("BY").to_matchable(),
                    Ref::keyword("RANGE").to_matchable(),
                    Bracketed::new(vec![Ref::new("FunctionSegment").to_matchable()]).to_matchable(),
                    Bracketed::new(vec![]).to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("PARTITION").to_matchable(),
                    Ref::keyword("BY").to_matchable(),
                    one_of(vec![
                        Sequence::new(vec![
                            Ref::keyword("RANGE").to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![
                                    Ref::new("ColumnReferenceSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![
                                    one_of(vec![
                                        Ref::new("RangePartitionDefinitionSegment").to_matchable(),
                                        Ref::new("RangePartitionIntervalSegment").to_matchable(),
                                    ])
                                    .to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                        Sequence::new(vec![
                            Ref::keyword("LIST").to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![
                                    Ref::new("ColumnReferenceSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![
                                    Ref::new("ListPartitionDefinitionSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    doris.add([(
        "RangePartitionDefinitionSegment".into(),
        NodeMatcher::new(SyntaxKind::RangePartitionDefinition, |_| {
            Sequence::new(vec![
                Ref::keyword("PARTITION").to_matchable(),
                Ref::new("IfNotExistsGrammar").optional().to_matchable(),
                Ref::new("ObjectReferenceSegment").to_matchable(),
                Ref::keyword("VALUES").to_matchable(),
                one_of(vec![
                    Sequence::new(vec![
                        Ref::keyword("LESS").to_matchable(),
                        Ref::keyword("THAN").to_matchable(),
                        one_of(vec![
                            Ref::keyword("MAXVALUE").to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![Ref::new("LiteralGrammar").to_matchable()])
                                    .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                    Sequence::new(vec![
                        Bracketed::new(vec![
                            Bracketed::new(vec![
                                Delimited::new(vec![Ref::new("LiteralGrammar").to_matchable()])
                                    .to_matchable(),
                            ])
                            .to_matchable(),
                            Ref::new("CommaSegment").to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![Ref::new("LiteralGrammar").to_matchable()])
                                    .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Bracketed::new(vec![
                        Delimited::new(vec![
                            Sequence::new(vec![
                                Ref::new("QuotedLiteralSegment").to_matchable(),
                                Ref::new("EqualsSegment").to_matchable(),
                                Ref::new("QuotedLiteralSegment").to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    doris.add([(
        "RangePartitionIntervalSegment".into(),
        NodeMatcher::new(SyntaxKind::RangePartitionInterval, |_| {
            Sequence::new(vec![
                Ref::keyword("FROM").to_matchable(),
                Bracketed::new(vec![Ref::new("QuotedLiteralSegment").to_matchable()])
                    .to_matchable(),
                Ref::keyword("TO").to_matchable(),
                Bracketed::new(vec![Ref::new("QuotedLiteralSegment").to_matchable()])
                    .to_matchable(),
                Ref::keyword("INTERVAL").to_matchable(),
                Ref::new("NumericLiteralSegment").to_matchable(),
                one_of(vec![
                    Ref::keyword("YEAR").to_matchable(),
                    Ref::keyword("MONTH").to_matchable(),
                    Ref::keyword("DAY").to_matchable(),
                    Ref::keyword("HOUR").to_matchable(),
                    Ref::keyword("MINUTE").to_matchable(),
                    Ref::keyword("SECOND").to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    doris.add([(
        "ListPartitionDefinitionSegment".into(),
        NodeMatcher::new(SyntaxKind::ListPartitionDefinition, |_| {
            Sequence::new(vec![
                Ref::keyword("PARTITION").to_matchable(),
                Ref::new("IfNotExistsGrammar").optional().to_matchable(),
                Ref::new("ObjectReferenceSegment").to_matchable(),
                Ref::keyword("VALUES").to_matchable(),
                Ref::keyword("IN").to_matchable(),
                Bracketed::new(vec![
                    Delimited::new(vec![
                        one_of(vec![
                            Bracketed::new(vec![
                                Delimited::new(vec![Ref::new("LiteralGrammar").to_matchable()])
                                    .to_matchable(),
                            ])
                            .to_matchable(),
                            Ref::new("LiteralGrammar").to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    doris.add([(
        "DistributionSegment".into(),
        NodeMatcher::new(SyntaxKind::DistributionSegment, |_| {
            Sequence::new(vec![
                Ref::keyword("DISTRIBUTED").to_matchable(),
                Ref::keyword("BY").to_matchable(),
                one_of(vec![
                    Sequence::new(vec![
                        Ref::keyword("HASH").to_matchable(),
                        Bracketed::new(vec![
                            Delimited::new(vec![Ref::new("ColumnReferenceSegment").to_matchable()])
                                .to_matchable(),
                        ])
                        .to_matchable(),
                        Sequence::new(vec![
                            Ref::keyword("BUCKETS").to_matchable(),
                            one_of(vec![
                                Ref::new("NumericLiteralSegment").to_matchable(),
                                Ref::keyword("AUTO").to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .config(|this| this.optional())
                        .to_matchable(),
                    ])
                    .to_matchable(),
                    Sequence::new(vec![
                        Ref::keyword("RANDOM").to_matchable(),
                        Sequence::new(vec![
                            Ref::keyword("BUCKETS").to_matchable(),
                            one_of(vec![
                                Ref::new("NumericLiteralSegment").to_matchable(),
                                Ref::keyword("AUTO").to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .config(|this| this.optional())
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    doris.add([(
        "RollupSegment".into(),
        NodeMatcher::new(SyntaxKind::RollupSegment, |_| {
            Sequence::new(vec![
                Ref::keyword("ROLLUP").to_matchable(),
                Bracketed::new(vec![
                    Delimited::new(vec![
                        Sequence::new(vec![
                            Ref::new("ObjectReferenceSegment").to_matchable(),
                            Bracketed::new(vec![
                                Delimited::new(vec![
                                    Ref::new("ColumnReferenceSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                            Sequence::new(vec![
                                Ref::keyword("DUPLICATE").to_matchable(),
                                Ref::keyword("KEY").to_matchable(),
                                Bracketed::new(vec![
                                    Delimited::new(vec![
                                        Ref::new("ColumnReferenceSegment").to_matchable(),
                                    ])
                                    .to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .config(|this| this.optional())
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    doris.add([(
        "IndexDefinitionSegment".into(),
        NodeMatcher::new(SyntaxKind::IndexDefinition, |_| {
            Sequence::new(vec![
                Ref::keyword("INDEX").to_matchable(),
                Ref::new("IfNotExistsGrammar").optional().to_matchable(),
                Ref::new("IndexReferenceSegment").to_matchable(),
                Bracketed::new(vec![
                    Delimited::new(vec![Ref::new("ColumnReferenceSegment").to_matchable()])
                        .to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("USING").to_matchable(),
                    one_of(vec![
                        Ref::keyword("INVERTED").to_matchable(),
                        Ref::keyword("BITMAP").to_matchable(),
                        Ref::keyword("BLOOM_FILTER").to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("PROPERTIES").to_matchable(),
                    Bracketed::new(vec![
                        Delimited::new(vec![
                            Sequence::new(vec![
                                Ref::new("QuotedLiteralSegment").to_matchable(),
                                Ref::new("EqualsSegment").to_matchable(),
                                Ref::new("QuotedLiteralSegment").to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("COMMENT").to_matchable(),
                    Ref::new("QuotedLiteralSegment").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    doris.replace_grammar(
        "DropTableStatementSegment",
        Sequence::new(vec![
            Ref::keyword("DROP").to_matchable(),
            Ref::keyword("TABLE").to_matchable(),
            Ref::new("IfExistsGrammar").optional().to_matchable(),
            Ref::new("TableReferenceSegment").to_matchable(),
            Sequence::new(vec![Ref::keyword("FORCE").to_matchable()])
                .config(|this| this.optional())
                .to_matchable(),
        ])
        .to_matchable(),
    );
    doris.replace_grammar(
        "InsertStatementSegment",
        Sequence::new(vec![
            Ref::keyword("INSERT").to_matchable(),
            Ref::keyword("INTO").optional().to_matchable(),
            Ref::new("TableReferenceSegment").to_matchable(),
            Sequence::new(vec![
                Ref::keyword("PARTITION").to_matchable(),
                Bracketed::new(vec![
                    Delimited::new(vec![Ref::new("SingleIdentifierGrammar").to_matchable()])
                        .to_matchable(),
                ])
                .to_matchable(),
            ])
            .config(|this| this.optional())
            .to_matchable(),
            Sequence::new(vec![
                Ref::keyword("WITH").to_matchable(),
                Ref::keyword("LABEL").to_matchable(),
                Ref::new("SingleIdentifierGrammar").to_matchable(),
            ])
            .config(|this| this.optional())
            .to_matchable(),
            Ref::new("BracketedColumnReferenceListGrammar")
                .optional()
                .to_matchable(),
            one_of(vec![
                Ref::new("ValuesClauseSegment").to_matchable(),
                Ref::new("SelectableGrammar").to_matchable(),
            ])
            .to_matchable(),
        ])
        .to_matchable(),
    );
    doris
}
