//! Apache Flink SQL dialect, based on ANSI.
use super::ansi;
use crate::flink_keywords::{RESERVED_KEYWORDS, UNRESERVED_KEYWORDS};
use sqruff_lib_core::dialects::Dialect;
use sqruff_lib_core::dialects::init::{DialectConfig, DialectKind};
use sqruff_lib_core::dialects::syntax::SyntaxKind;
use sqruff_lib_core::helpers::{Config, ToMatchable};
use sqruff_lib_core::parser::grammar::Ref;
use sqruff_lib_core::parser::grammar::anyof::{one_of, optionally_bracketed};
use sqruff_lib_core::parser::grammar::delimited::Delimited;
use sqruff_lib_core::parser::grammar::sequence::{Bracketed, Sequence};
use sqruff_lib_core::parser::lexer::Matcher;
use sqruff_lib_core::parser::matchable::MatchableTrait;
use sqruff_lib_core::parser::node_matcher::NodeMatcher;
use sqruff_lib_core::parser::parsers::{StringParser, TypedParser};
use sqruff_lib_core::value::Value;
sqruff_lib_core::dialect_config!(FlinkDialectConfig {});
pub fn dialect(config: Option<&Value>) -> Dialect {
    let _config: FlinkDialectConfig = config
        .map(FlinkDialectConfig::from_value)
        .unwrap_or_default();
    raw_dialect().config(|dialect| dialect.expand())
}
pub fn raw_dialect() -> Dialect {
    let mut flink = ansi::raw_dialect();
    flink.name = DialectKind::Flink;
    flink
        .sets_mut("reserved_keywords")
        .extend(RESERVED_KEYWORDS.split_whitespace());
    flink
        .sets_mut("unreserved_keywords")
        .extend(UNRESERVED_KEYWORDS.split_whitespace());
    flink.patch_lexer_matchers(vec![Matcher::regex("inline_comment",r#"(--)[^\n]*"#, SyntaxKind::InlineComment),Matcher::regex("back_quote",r#"`([^`]|``)*`"#, SyntaxKind::BackQuote),Matcher::legacy("numeric_literal", |s| s.starts_with(|ch: char| ch == '.' || ch == '-' || ch.is_ascii_alphanumeric()), r#"(?>(?>\d+\.\d+|\d+\.|\.\d+)([eE][+-]?\d+)?([dDfF]|BD|bd)?|\d+[eE][+-]?\d+([dDfF]|BD|bd)?|\d+([dDfFlLsSyY]|BD|bd)?)((?<=\.)|(?=\b))"#, SyntaxKind::NumericLiteral),Matcher::regex("single_quote",r#"'([^'\\]|\\.)*'"#, SyntaxKind::SingleQuote),Matcher::regex("equals",r#"==|="#, SyntaxKind::RawComparisonOperator),]);
    flink.sets_mut("datetime_units").clear();
    flink.sets_mut("datetime_units").extend([
        "YEAR",
        "MONTH",
        "DAY",
        "HOUR",
        "MINUTE",
        "SECOND",
        "MICROSECOND",
        "MILLISECOND",
        "NANOSECOND",
        "EPOCH",
        "DECADE",
        "CENTURY",
        "MILLENNIUM",
        "QUARTER",
        "WEEK",
        "DOW",
        "ISODOW",
        "DOY",
        "ISOYEAR",
    ]);
    flink.sets_mut("bare_functions").clear();
    flink.sets_mut("bare_functions").extend([
        "CURRENT_DATE",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_USER",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "NOW",
        "CURRENT_WATERMARK",
        "PROCTIME",
    ]);
    flink.bracket_sets_mut("angle_bracket_pairs").extend([(
        "angle",
        "StartAngleBracketSegment",
        "EndAngleBracketSegment",
        false,
    )]);
    flink.add([
        (
            "StartAngleBracketSegment".into(),
            StringParser::new("<", SyntaxKind::StartAngleBracket)
                .to_matchable()
                .into(),
        ),
        (
            "EndAngleBracketSegment".into(),
            StringParser::new(">", SyntaxKind::EndAngleBracket)
                .to_matchable()
                .into(),
        ),
        (
            "BackQuotedIdentifierSegment".into(),
            TypedParser::new(SyntaxKind::BackQuote, SyntaxKind::QuotedIdentifier)
                .to_matchable()
                .into(),
        ),
        (
            "DoubleEqualsSegment".into(),
            StringParser::new("==", SyntaxKind::DoubleEquals)
                .to_matchable()
                .into(),
        ),
        (
            "CreateTableConnectorOptionsSegment".into(),
            Sequence::new(vec![
                Ref::keyword("WITH").to_matchable(),
                Bracketed::new(vec![
                    Delimited::new(vec![
                        Sequence::new(vec![
                            one_of(vec![
                                Ref::new("QuotedLiteralSegment").to_matchable(),
                                Ref::new("NakedIdentifierSegment").to_matchable(),
                            ])
                            .to_matchable(),
                            one_of(vec![
                                Ref::new("EqualsSegment").to_matchable(),
                                Ref::new("DoubleEqualsSegment").to_matchable(),
                            ])
                            .to_matchable(),
                            one_of(vec![
                                Ref::new("QuotedLiteralSegment").to_matchable(),
                                Ref::new("NakedIdentifierSegment").to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "WatermarkDefinitionSegment".into(),
            Sequence::new(vec![
                Ref::keyword("WATERMARK").to_matchable(),
                Ref::keyword("FOR").to_matchable(),
                Ref::new("ColumnReferenceSegment").to_matchable(),
                Ref::keyword("AS").to_matchable(),
                Ref::new("ExpressionSegment").to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "ComputedColumnDefinitionSegment".into(),
            Sequence::new(vec![
                Ref::new("NakedIdentifierSegment").to_matchable(),
                Ref::keyword("AS").to_matchable(),
                Ref::new("ExpressionSegment").to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("COMMENT").to_matchable(),
                    Ref::new("QuotedLiteralSegment").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "MetadataColumnDefinitionSegment".into(),
            Sequence::new(vec![
                Ref::new("NakedIdentifierSegment").to_matchable(),
                Ref::new("DatatypeSegment").to_matchable(),
                Ref::keyword("METADATA").to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("FROM").to_matchable(),
                    Ref::new("QuotedLiteralSegment").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
                Sequence::new(vec![Ref::keyword("VIRTUAL").to_matchable()])
                    .config(|this| this.optional())
                    .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("COMMENT").to_matchable(),
                    Ref::new("QuotedLiteralSegment").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "FlinkTableConstraintSegment".into(),
            Sequence::new(vec![
                Sequence::new(vec![
                    Ref::keyword("CONSTRAINT").to_matchable(),
                    Ref::new("NakedIdentifierSegment").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
                Ref::keyword("PRIMARY").to_matchable(),
                Ref::keyword("KEY").to_matchable(),
                Bracketed::new(vec![
                    Delimited::new(vec![Ref::new("ColumnReferenceSegment").to_matchable()])
                        .to_matchable(),
                ])
                .to_matchable(),
                Ref::keyword("NOT").to_matchable(),
                Ref::keyword("ENFORCED").to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "PartitionDefinitionSegment".into(),
            Sequence::new(vec![
                Ref::keyword("PARTITIONED").to_matchable(),
                Ref::keyword("BY").to_matchable(),
                Bracketed::new(vec![
                    Delimited::new(vec![Ref::new("ColumnReferenceSegment").to_matchable()])
                        .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "DistributionDefinitionSegment".into(),
            one_of(vec![
                Sequence::new(vec![
                    Ref::keyword("DISTRIBUTED").to_matchable(),
                    Ref::keyword("BY").to_matchable(),
                    one_of(vec![
                        Ref::keyword("HASH").to_matchable(),
                        Ref::keyword("RANGE").to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                    Bracketed::new(vec![
                        Delimited::new(vec![Ref::new("ColumnReferenceSegment").to_matchable()])
                            .to_matchable(),
                    ])
                    .to_matchable(),
                    Sequence::new(vec![
                        Ref::keyword("INTO").to_matchable(),
                        Ref::new("NumericLiteralSegment").to_matchable(),
                        Ref::keyword("BUCKETS").to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("DISTRIBUTED").to_matchable(),
                    Ref::keyword("INTO").to_matchable(),
                    Ref::new("NumericLiteralSegment").to_matchable(),
                    Ref::keyword("BUCKETS").to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "LikeOptionsSegment".into(),
            Delimited::new(vec![
                one_of(vec![
                    Sequence::new(vec![
                        one_of(vec![
                            Ref::keyword("INCLUDING").to_matchable(),
                            Ref::keyword("EXCLUDING").to_matchable(),
                        ])
                        .to_matchable(),
                        one_of(vec![
                            Ref::keyword("ALL").to_matchable(),
                            Ref::keyword("CONSTRAINTS").to_matchable(),
                            Ref::keyword("DISTRIBUTION").to_matchable(),
                            Ref::keyword("PARTITIONS").to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                    Sequence::new(vec![
                        one_of(vec![
                            Ref::keyword("INCLUDING").to_matchable(),
                            Ref::keyword("EXCLUDING").to_matchable(),
                            Ref::keyword("OVERWRITING").to_matchable(),
                        ])
                        .to_matchable(),
                        one_of(vec![
                            Ref::keyword("GENERATED").to_matchable(),
                            Ref::keyword("OPTIONS").to_matchable(),
                            Ref::keyword("WATERMARKS").to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
        (
            "LikeClauseSegment".into(),
            Sequence::new(vec![
                Ref::keyword("LIKE").to_matchable(),
                Ref::new("TableReferenceSegment").to_matchable(),
                Bracketed::new(vec![Ref::new("LikeOptionsSegment").to_matchable()])
                    .config(|this| this.optional())
                    .to_matchable(),
            ])
            .to_matchable()
            .into(),
        ),
    ]);
    flink.add([(
        "SingleIdentifierGrammar".into(),
        one_of(vec![
            Ref::new("NakedIdentifierSegment").to_matchable(),
            Ref::new("QuotedIdentifierSegment").to_matchable(),
            Ref::new("BackQuotedIdentifierSegment").to_matchable(),
        ])
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "CreateTableStatementSegment".into(),
        NodeMatcher::new(SyntaxKind::CreateTableStatement, |_| {
            Sequence::new(vec![
                Ref::keyword("CREATE").to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("OR").to_matchable(),
                    Ref::keyword("REPLACE").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
                Ref::keyword("TABLE").to_matchable(),
                Ref::new("IfNotExistsGrammar").optional().to_matchable(),
                Ref::new("TableReferenceSegment").to_matchable(),
                one_of(vec![
                    Sequence::new(vec![
                        Bracketed::new(vec![
                            Delimited::new(vec![
                                one_of(vec![
                                    Ref::new("ColumnDefinitionSegment").to_matchable(),
                                    Ref::new("MetadataColumnDefinitionSegment").to_matchable(),
                                    Ref::new("ComputedColumnDefinitionSegment").to_matchable(),
                                    Ref::new("WatermarkDefinitionSegment").to_matchable(),
                                    Ref::new("FlinkTableConstraintSegment").to_matchable(),
                                ])
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                        Sequence::new(vec![
                            Ref::keyword("COMMENT").to_matchable(),
                            Ref::new("QuotedLiteralSegment").to_matchable(),
                        ])
                        .config(|this| this.optional())
                        .to_matchable(),
                        Ref::new("PartitionDefinitionSegment")
                            .optional()
                            .to_matchable(),
                        Ref::new("DistributionDefinitionSegment")
                            .optional()
                            .to_matchable(),
                        Ref::new("CreateTableConnectorOptionsSegment")
                            .optional()
                            .to_matchable(),
                        Ref::new("LikeClauseSegment").optional().to_matchable(),
                    ])
                    .to_matchable(),
                    Sequence::new(vec![
                        Ref::keyword("AS").to_matchable(),
                        optionally_bracketed(vec![Ref::new("SelectableGrammar").to_matchable()])
                            .to_matchable(),
                    ])
                    .to_matchable(),
                    Ref::new("LikeClauseSegment").to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "CreateCatalogStatementSegment".into(),
        NodeMatcher::new(SyntaxKind::CreateCatalogStatement, |_| {
            Sequence::new(vec![
                Ref::keyword("CREATE").to_matchable(),
                Ref::keyword("CATALOG").to_matchable(),
                Ref::new("NakedIdentifierSegment").to_matchable(),
                Ref::new("CreateTableConnectorOptionsSegment").to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "CreateDatabaseStatementSegment".into(),
        NodeMatcher::new(SyntaxKind::CreateDatabaseStatement, |_| {
            Sequence::new(vec![
                Ref::keyword("CREATE").to_matchable(),
                Ref::keyword("DATABASE").to_matchable(),
                Ref::new("IfNotExistsGrammar").optional().to_matchable(),
                Ref::new("ObjectReferenceSegment").to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("COMMENT").to_matchable(),
                    Ref::new("QuotedLiteralSegment").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
                Ref::new("CreateTableConnectorOptionsSegment")
                    .optional()
                    .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "DescribeStatementSegment".into(),
        NodeMatcher::new(SyntaxKind::DescribeStatement, |_| {
            Sequence::new(vec![
                Ref::keyword("DESCRIBE").to_matchable(),
                Ref::new("TableReferenceSegment").to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "ExplainStatementSegment".into(),
        NodeMatcher::new(SyntaxKind::ExplainStatement, |_| {
            Sequence::new(vec![
                Ref::keyword("EXPLAIN").to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("PLAN").to_matchable(),
                    Ref::keyword("FOR").to_matchable(),
                ])
                .config(|this| this.optional())
                .to_matchable(),
                Ref::new("SelectableGrammar").to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "ShowStatementsSegment".into(),
        NodeMatcher::new(SyntaxKind::ShowStatement, |_| {
            Sequence::new(vec![
                Ref::keyword("SHOW").to_matchable(),
                one_of(vec![
                    Ref::keyword("CATALOGS").to_matchable(),
                    Ref::keyword("DATABASES").to_matchable(),
                    Ref::keyword("TABLES").to_matchable(),
                    Ref::keyword("VIEWS").to_matchable(),
                    Ref::keyword("FUNCTIONS").to_matchable(),
                    Ref::keyword("MODULES").to_matchable(),
                    Ref::keyword("JARS").to_matchable(),
                    Ref::keyword("JOBS").to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "UseStatementSegment".into(),
        NodeMatcher::new(SyntaxKind::UseStatement, |_| {
            one_of(vec![
                Sequence::new(vec![
                    Ref::keyword("USE").to_matchable(),
                    Ref::keyword("CATALOG").to_matchable(),
                    Ref::new("ObjectReferenceSegment").to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("USE").to_matchable(),
                    Ref::new("ObjectReferenceSegment").to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "RowDataTypeSegment".into(),
        NodeMatcher::new(SyntaxKind::RowDataType, |_| {
            Sequence::new(vec![
                Ref::keyword("ROW").to_matchable(),
                one_of(vec![
                    Bracketed::new(vec![
                        Delimited::new(vec![
                            Sequence::new(vec![
                                Ref::new("SingleIdentifierGrammar").to_matchable(),
                                Ref::new("DatatypeSegment").to_matchable(),
                                Sequence::new(vec![
                                    Ref::keyword("COMMENT").to_matchable(),
                                    Ref::new("QuotedLiteralSegment").to_matchable(),
                                ])
                                .config(|this| this.optional())
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .config(|this| this.bracket_type = "angle")
                    .config(|this| this.bracket_pairs_set = "angle_bracket_pairs")
                    .to_matchable(),
                    Bracketed::new(vec![
                        Delimited::new(vec![
                            Sequence::new(vec![
                                Ref::new("SingleIdentifierGrammar").to_matchable(),
                                Ref::new("DatatypeSegment").to_matchable(),
                                Sequence::new(vec![
                                    Ref::keyword("COMMENT").to_matchable(),
                                    Ref::new("QuotedLiteralSegment").to_matchable(),
                                ])
                                .config(|this| this.optional())
                                .to_matchable(),
                            ])
                            .to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .config(|this| this.bracket_type = "round")
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    flink.add([(
        "DatatypeSegment".into(),
        NodeMatcher::new(SyntaxKind::DataType, |_| {
            one_of(vec![
                Ref::new("RowDataTypeSegment").to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("ARRAY").to_matchable(),
                    Bracketed::new(vec![Ref::new("DatatypeSegment").to_matchable()])
                        .config(|this| this.bracket_type = "angle")
                        .config(|this| this.bracket_pairs_set = "angle_bracket_pairs")
                        .to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("MAP").to_matchable(),
                    Bracketed::new(vec![
                        Sequence::new(vec![
                            Ref::new("DatatypeSegment").to_matchable(),
                            Ref::new("CommaSegment").to_matchable(),
                            Ref::new("DatatypeSegment").to_matchable(),
                        ])
                        .to_matchable(),
                    ])
                    .config(|this| this.bracket_type = "angle")
                    .config(|this| this.bracket_pairs_set = "angle_bracket_pairs")
                    .to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::keyword("MULTISET").to_matchable(),
                    Bracketed::new(vec![Ref::new("DatatypeSegment").to_matchable()])
                        .config(|this| this.bracket_type = "angle")
                        .config(|this| this.bracket_pairs_set = "angle_bracket_pairs")
                        .to_matchable(),
                ])
                .to_matchable(),
                ansi::raw_dialect()
                    .grammar("DatatypeSegment")
                    .match_grammar(&ansi::raw_dialect())
                    .unwrap(),
            ])
            .to_matchable()
        })
        .to_matchable()
        .into(),
    )]);
    // Flink watermarks use the combined interval form from upstream ANSI.
    flink.replace_grammar(
        "IntervalExpressionSegment",
        Sequence::new(vec![
            Ref::keyword("INTERVAL").to_matchable(),
            one_of(vec![
                Sequence::new(vec![
                    Ref::new("NumericLiteralSegment").to_matchable(),
                    one_of(vec![
                        Ref::new("QuotedLiteralSegment").to_matchable(),
                        Ref::new("DatetimeUnitSegment").to_matchable(),
                    ])
                    .to_matchable(),
                ])
                .to_matchable(),
                Sequence::new(vec![
                    Ref::new("QuotedLiteralSegment").to_matchable(),
                    one_of(vec![
                        Ref::new("QuotedLiteralSegment").to_matchable(),
                        Ref::new("DatetimeUnitSegment").to_matchable(),
                    ])
                    .config(|this| this.optional())
                    .to_matchable(),
                ])
                .to_matchable(),
            ])
            .to_matchable(),
        ])
        .to_matchable(),
    );
    flink.replace_grammar(
        "StatementSegment",
        flink
            .grammar("StatementSegment")
            .match_grammar(&flink)
            .unwrap()
            .copy(
                Some(vec![
                    Ref::new("CreateCatalogStatementSegment").to_matchable(),
                    Ref::new("CreateDatabaseStatementSegment").to_matchable(),
                    Ref::new("DescribeStatementSegment").to_matchable(),
                    Ref::new("ShowStatementsSegment").to_matchable(),
                ]),
                None,
                None,
                None,
                Vec::new(),
                false,
            ),
    );
    flink
}
