load("@crates//:defs.bzl", "all_crate_deps", "crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test_suite")

exports_files([
    "Cargo.toml",
    "test/fixtures/dialects/ansi/sqlfluff/select_in_multiline_comment.sql",
])

# Keep in sync with the features enabled by default in Cargo.toml.
ALL_FEATURES = [
    "athena",
    "bigquery",
    "clickhouse",
    "databricks",
    "db2",
    "duckdb",
    "exasol",
    "greenplum",
    "hive",
    "materialize",
    "mysql",
    "oracle",
    "postgres",
    "redshift",
    "snowflake",
    "sparksql",
    "sqlite",
    "starrocks",
    "teradata",
    "trino",
    "tsql",
    "vertica",
]

rust_library(
    name = "sqruff-lib-dialects",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ALL_FEATURES,
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True) + [
        "//crates/lib-core:sqruff-lib-core",
    ],
)

rust_test_suite(
    name = "dialect_tests",
    srcs = ["tests/dialects.rs"],
    crate_features = ALL_FEATURES,
    data = [
        ":test_fixtures",
        "Cargo.toml",
    ],
    deps = all_crate_deps(normal = True) + crate_deps([
        "configparser",
        "expect-test",
        "glob",
        "rayon",
    ]) + [
        ":sqruff-lib-dialects",
        "//crates/lib-core:sqruff-lib-core",
    ],
    env = {
        "SQRUFF_TEST_MANIFEST": "$(rootpath :Cargo.toml)",
    },
    size = "small",
)

filegroup(
    name = "machete_srcs",
    srcs = glob(
        [
            "src/**/*.rs",
            "tests/**/*.rs",
            "benches/**/*.rs",
        ],
        allow_empty = True,
    ) + ["Cargo.toml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_fixtures",
    srcs = glob(["test/**"]),
    visibility = ["//visibility:public"],
)
